/**
 * メーカー静的メタデータ
 *
 * DBには持たない補助情報（国コード、将来的にロゴパス等）。
 * 海外メーカー追加時に country を 'US', 'FI' 等に変更。
 */

export interface ManufacturerMeta {
  country: string;       // ISO 3166-1 alpha-2
  logo_path?: string;    // 将来用: '/images/makers/daiwa.svg'
}

export const MANUFACTURER_META: Record<string, ManufacturerMeta> = {
  attic:              { country: 'JP' },
  baitbreath:         { country: 'JP' },
  bassday:            { country: 'JP' },
  beat:               { country: 'JP' },
  berkley:            { country: 'JP' },  // 米国ブランドだが国内流通分
  blueblue:           { country: 'JP' },
  boreas:             { country: 'JP' },
  bottomup:           { country: 'JP' },
  bozles:             { country: 'JP' },
  breaden:            { country: 'JP' },
  carpenter:          { country: 'JP' },
  'cb-one':           { country: 'JP' },
  coreman:            { country: 'JP' },
  'crazy-ocean':      { country: 'JP' },
  'd-claw':           { country: 'JP' },
  daiwa:              { country: 'JP' },
  deepliner:          { country: 'JP' },
  deps:               { country: 'JP' },
  dranckrazy:         { country: 'JP' },
  dreemup:            { country: 'JP' },
  drt:                { country: 'JP' },
  dstyle:             { country: 'JP' },
  duel:               { country: 'JP' },
  duo:                { country: 'JP' },
  ecogear:            { country: 'JP' },
  engine:             { country: 'JP' },
  evergreen:          { country: 'JP' },
  'flash-union':      { country: 'JP' },
  forest:             { country: 'JP' },
  gamakatsu:          { country: 'JP' },
  gancraft:           { country: 'JP' },
  'gary-yamamoto':    { country: 'JP' },
  geecrack:           { country: 'JP' },
  grassroots:         { country: 'JP' },
  harimitsu:          { country: 'JP' },
  hayabusa:           { country: 'JP' },
  hideup:             { country: 'JP' },
  hmkl:               { country: 'JP' },
  hots:               { country: 'JP' },
  apia:               { country: 'JP' },
  ima:                { country: 'JP' },
  imakatsu:           { country: 'JP' },
  issei:              { country: 'JP' },
  itocraft:           { country: 'JP' },
  'ivy-line':         { country: 'JP' },
  'ja-do':            { country: 'JP' },
  jackall:            { country: 'JP' },
  jackson:            { country: 'JP' },
  jumprize:           { country: 'JP' },
  'jungle-gym':       { country: 'JP' },
  keitech:            { country: 'JP' },
  littlejack:         { country: 'JP' },
  longin:             { country: 'JP' },
  luckycraft:         { country: 'JP' },
  madness:            { country: 'JP' },
  majorcraft:         { country: 'JP' },
  maria:              { country: 'JP' },
  'mc-works':         { country: 'JP' },
  megabass:           { country: 'JP' },
  mukai:              { country: 'JP' },
  'nature-boys':      { country: 'JP' },
  noike:              { country: 'JP' },
  nories:             { country: 'JP' },
  'north-craft':      { country: 'JP' },
  osp:                { country: 'JP' },
  palms:              { country: 'JP' },
  pazdesign:          { country: 'JP' },
  pickup:             { country: 'JP' },
  'pozidrive-garage': { country: 'JP' },
  raid:               { country: 'JP' },
  rapala:             { country: 'JP' },  // フィンランドブランドだが国内流通分
  reins:              { country: 'JP' },
  sawamura:           { country: 'JP' },
  'sea-falcon':       { country: 'JP' },
  'seafloor-control': { country: 'JP' },
  shimano:            { country: 'JP' },
  shout:              { country: 'JP' },
  smith:              { country: 'JP' },
  souls:              { country: 'JP' },
  tacklehouse:        { country: 'JP' },
  thirtyfour:         { country: 'JP' },
  tict:               { country: 'JP' },
  tiemco:             { country: 'JP' },
  valkein:            { country: 'JP' },
  valleyhill:         { country: 'JP' },
  viva:               { country: 'JP' },
  xesta:              { country: 'JP' },
  yamashita:          { country: 'JP' },
  yarie:              { country: 'JP' },
  zeake:              { country: 'JP' },
  'zero-dragon':      { country: 'JP' },
  zipbaits:           { country: 'JP' },
};

export function getManufacturerCountry(slug: string): string {
  return MANUFACTURER_META[slug]?.country ?? 'JP';
}
