// src/data/ranking-descriptions-en.ts
// English ranking page editorial descriptions
// Keys: {fish_slug}-{type_slug} (e.g., seabass-minnow)
// 331 entries — mirrors ranking-descriptions.ts
export const rankingDescriptionsEn: Record<string, string> = {
  'seabass-minnow':
    'Minnows deliver the best baitfish imitation when targeting Japanese Seabass in rivers and tidal flats. Drift them just below the surface and let the current impart a rolling action to trigger strikes. Size selection in the 90–120 mm range should match the prevailing forage.',
  'seabass-vibration':
    'Lipless crankbaits let you cover water from bottom to mid-column efficiently when chasing Japanese Seabass. In autumn, a fast retrieve triggers reaction strikes, while a dead-slow crawl near bottom with tight wobble excels in winter. They are proven performers around bridge pilings and shadow lines.',
  'seabass-sinking-pencil':
    'Sinking pencils shine on the drift and slow retrieve for Japanese Seabass. Letting the current sweep them in an S-curve faithfully mimics a wounded baitfish. Essential for trophy hunting on surf and river mouths, they also excel under dock lights at night.',
  'seabass-metal-vib':
    'Metal vibs—often called iron-plate lures in Japan—combine casting distance with fast sink rates. Lift-and-fall along the bottom sends strong vibrations that pull Seabass from a wide area. Even in winter when activity drops, these lures draw bites; they are especially effective during baitfish migrations in rivers.',
  'seabass-pencilbait':
    'A pencil bait\'s walk-the-dog action directly targets the predatory instinct of Japanese Seabass. Work it side to side on the surface and pause—strikes often come right at the stop. Indispensable during autumn Inakko (juvenile mullet) patterns and morning-twilight blitzes, it delivers high visual excitement.',
  'seabass-popper':
    'A popper\'s explosive report can pull Japanese Seabass to the surface from depth. The cupped face pushes water to create sound and spray that attract fish from far away. When sardines or Konoshiro shad are being driven to the surface, nothing beats a popper for topwater action.',
  'seabass-metal-jig':
    'When targeting Japanese Seabass from surf or rocky shores, a metal jig\'s casting distance decides the game. On shallow surf, skip a slow-style jig across the surface; in river mouths, use vertical lift-and-fall. Jigs in the 30–50 g range offer the best versatility where bluerunners also roam.',
  'seabass-spintail':
    'Spintail jigs combine blade flash with a soft-body\'s fluid action. They stimulate both the lateral line and vision of Seabass, making them especially effective during low-light conditions at dawn and dusk. A slow retrieve with a quivering tail also triggers bites on the fall.',
  'seabass-bigbait':
    'Big baits unleash their full power during Konoshiro shad or mullet seasons for Japanese Seabass. Their weight favors close-range casts over distance, banking on sheer presence to target trophy fish. The wobble generated by multi-jointed bodies displaces serious water, pulling in fish over 90 cm.',
  'seabass-worm':
    'Soft plastics are the most persistent presentation for lethargic Japanese Seabass. A dead-slow shad-tail retrieve generates just enough tail vibration to coax a bite. Slow-rolling or dragging bottom around structure is the trump card when hard baits draw no response.',
  'seabass-jighead':
    'A jig head rig offers pinpoint accuracy for targeting Japanese Seabass. Head weight selection—typically 1–10 g—matched to depth and current is the key variable. Swimming or lift-and-fall techniques in current let you fine-tune the bite window.',
  'seabass-blade-bait':
    'The thin metal body\'s vibration and flash are the hallmarks of blade baits. They produce stable vibration at any speed and remain effective year-round. For shade-line attacks around bridge pilings and tetrapods, a vertical lift-and-fall lifts fish off the bottom.',
  'seabass-shad':
    'Shad plugs match the compact silhouette of Haku (juvenile mullet) and Ami (mysid shrimp) that Seabass feed on. During micro-bait patterns, a small shad on a dead-slow retrieve draws strikes from fish that ignore everything else. The combined roll action and subtle vibration seal the deal.',
  'seabass-jointed-bait':
    'The S-curve action born from a jointed bait\'s hinge stimulates the predatory instinct of Japanese Seabass. Its seductive dead-slow shimmy is the main weapon—simply drifting it in current can trigger bites from trophy fish. This is a lure favored by dedicated trophy hunters, meant to be fished slowly and deliberately.',
  'seabass-crankbait':
    'Crankbaits use their lip to control diving depth while generating a steady wobble. The tangible feel of the lip grabbing water in current makes them intuitive to fish, and they excel at efficiently covering shallow zones. Deflecting off riprap and structure creates the trigger that provokes strikes.',
  'seabass-swimbait':
    'Swimbaits fool pressured Japanese Seabass with natural swimming action and realistic profiles. From one-piece to multi-jointed designs, matching the situation is key. They swim convincingly even at slow speeds and can be worked from bottom to surface across any depth.',
  'black-bass-worm':
    'Soft plastics are both the foundation and the deepest rabbit hole of bass fishing. Texas rigs, drop-shots, Neko rigs—the versatility is endless. The slower you work them along structure changes, the more bites you draw even on highly pressured waters. Size, color, and material selection determine your catch rate.',
  'black-bass-crankbait':
    'Crankbaits are the ultimate search tool for covering vast areas efficiently. Lip shape dictates diving depth, so tracing them tight along weed tops and rock ledges is essential. The erratic deflection when the lip contacts hard bottom triggers instinctive bass strikes.',
  'black-bass-minnow':
    'Minnows come into their own for sight-fishing and spawning-season Largemouth Bass. Flash and roll action agitate bedding fish, while the natural presentation fools even pressured bass. Jerk-and-pause along shallow cover edges is the standard tactic.',
  'black-bass-spinnerbait':
    'Spinnerbaits combine snag resistance for punching through cover with blade flash—a true all-around weapon. Especially lethal in stained water and low-light mornings, they search wide swaths of water quickly. Slow-rolling near the bottom draws big fish.',
  'black-bass-vibration':
    'Lipless crankbaits are high-powered search baits that perform across all seasons. Fast retrieves probe the mid-column while bottom contact triggers reaction bites. They shine brightest when depth is hard to read, such as post-turnover in fall or the depths of winter.',
  'black-bass-rubber-jig':
    'Rubber jigs specialize in reaching big bass buried deep in cover. The skirt\'s motion suggests bluegill or crawfish, and a slow fall gives the fish time to commit. Trailer selection drastically alters the action, so fine-tuning directly impacts your results.',
  'black-bass-bigbait':
    'Big baits are tools for selectively targeting trophy bass. A large silhouette and heavy water displacement awaken the predatory instinct of lunker fish. They produce best during pre-spawn in spring and the fall feed-up, demanding strategic use on expansive waters to single out monster-sized fish.',
  'black-bass-shad':
    'Shad-style soft baits excel at matching the Wakasagi (pond smelt) and Moroko (minnow) that bass feed on. The tight wobble-and-roll balance translates directly into bites, even when water temperatures drop and activity slows. The ability to cover depths from deep to shallow is a major asset.',
  'black-bass-popper':
    'A popper explosion on the surface is one of bass fishing\'s most thrilling moments. The cupped face generates sound and rings that trigger the predatory instinct of bass, bringing them up through the water column. On shallow morning and evening bites around vegetation, a measured pause-and-pop cadence is the key.',
  'black-bass-swimbait':
    'Swimbaits offer a finesse presentation that covers shallow to deep water evenly. Worm-like natural materials catch the current and roll the tail, fooling even line-shy bass. Weight configuration and retrieve speed together control the running depth.',
  'black-bass-chatterbait':
    'Chatterbaits combine high-frequency blade vibration with trailer movement for a compound action that bass find irresistible. They cut through weeds and cover cleanly, making them user-friendly in dense structure. Especially dominant around the spawn, they show high selectivity for big fish.',
  'black-bass-pencilbait':
    'A pencil bait\'s walk-the-dog action flips the aggression switch in bass. Work it slowly with side-to-side headshakes, pausing to create a feeding window. It is most effective during topwater-sensitive dawn periods and when baitfish push to the surface at dusk.',
  'black-bass-buzzbait':
    'The continuous splashing and churning of a buzzbait\'s propeller calls bass to the surface. High-speed surface retrieves along seawalls and reed edges dramatically increase blowups. On summer mornings and overcast days it can produce all day, condensing the thrill of topwater fishing into every cast.',
  'black-bass-crawler-bait':
    'Crawler baits use their arms to push water, creating a unique wake and sound that draws bass in. They keep working even at ultra-slow speeds, making them effective during low-activity periods and under high-temperature pressure. Dawn on a calm surface is prime time for this style.',
  'black-bass-frog':
    'Frogs make it possible to fish over weed mats and lily pads where no other lure can go. To haul big bass up through heavy cover, heavy line is a must. Pause length and the moment after splashdown are the critical factors that trigger a strike.',
  'black-bass-jointed-bait':
    'The S-curve slalom of a jointed bait replicates the swimming motion of living prey with uncanny realism. Its sinuous dead-slow action visually stimulates spawning-related big bass. Add a jerk for erratic movement and you can also trigger reaction strikes—a multi-dimensional lure.',
  'black-bass-metal-vib':
    'Metal vibs are purpose-built for quickly probing deep-water bottom. Lift-and-fall in the vertical plane tempts bass during the pause. In the coldest water of winter when targeting deep fish, this is one of the most effective vibration-class patterns available.',
  'black-bass-i-shape':
    'I-shape lures swim in a near-straight line with minimal action—a secret weapon against pressured bass. Simply dead-slow retrieving a slim shad or pin-tail worm just below the surface creates a dazed, drifting motion that triggers the predatory instinct. They prove their worth on clear, high-pressure fisheries.',
  'black-bass-spintail':
    'Spintail jigs combine a soft body with blade flash to appeal through both vibration and sight. Slow-rolling through the mid-column is the bread-and-butter technique, with the blade\'s reflected light flipping the feed switch. Their unique action draws bites even on pressured waters.',
  'black-bass-propbait':
    'The sound and surface ripples from a prop bait\'s spinning blade attract bass from a wide area. Combining pauses with short twitches to deliberately create feeding windows is the key to success. Focused morning and evening sessions let you efficiently target quality fish on the surface.',
  'black-bass-sinking-pencil':
    'Sinking pencils trigger bites with their shimmer and horizontal posture during the fall. Letting out slack for a fluttering, irregular descent draws reaction strikes. Pause during a slow mid-column retrieve and trailing bass commit on the drop.',
  'black-bass-blade-bait':
    'Blade baits weaponize the intense vibration and flash of a thin metal body. Vertical lift-and-fall jigging is devastating on deep bass, capable of drawing bites even in the coldest water of winter. Their compact silhouette relative to weight is an added advantage.',
  'black-bass-topwater':
    'Topwater fishing—where you see the bass blow up on your lure—delivers the ultimate adrenaline rush. Concentrate casts during early morning calm to draw aggressive surface strikes from shallow-holding big bass. Lure type matters less than timing and spot selection.',
  'black-bass-jighead':
    'A jig head rig paired with a shad or curly-tail and fished on a swimming retrieve is the standard approach. Light heads swim through shallows; heavier heads with a drop reach deep bottom. The freedom to dial in any depth while reading bottom contours makes this rig incredibly versatile.',
  'trout-spoon':
    'Spoons are the origin and most versatile lure in trout fishing. Weight and size adapt to current speed and depth, producing actions from slow rolls to fast retrieves. Flash-reflecting overcast skies or early mornings tend to concentrate strikes.',
  'trout-minnow':
    'Trout minnows work from mountain streams to managed ponds. Heavy-sinking types hold their depth in fast current, with a flash-and-roll action that excels on Char and Yamame. The skill of drifting the lure into slack water behind boulders directly affects your catch.',
  'trout-crankbait':
    'Trout crankbaits shine during dead-slow presentations at managed fisheries. The lip stabilizes the diving depth while generating subtle wobble that triggers even lethargic Rainbow Trout. Just slightly reducing retrieve speed can make a dramatic difference in getting bites.',
  'trout-spinner':
    'The spinning blade and flash of a spinner is the fastest route to a trout\'s reaction strike. Adjusting retrieve speed so the blade stays spinning steadily in current is fundamental—the moment it stalls, the bites stop. An upstream cast retrieved back down (up-cross technique) is the classic method.',
  'trout-vibration':
    'Trout-sized lipless crankbaits offer the mobility to search a wide depth range for pressured fish at managed fisheries. Focus on micro-class sizes during low-light periods with a slow retrieve for consistent results. Strikes frequently come on the fall, so line tension management is critical.',
  'trout-sinking-pencil':
    'Sinking pencils counter trout wariness with a natural, drifting presentation. The swaying fall suggests a weakened baitfish and triggers predatory instinct. In mountain streams, dropping one into the white water of a riffle and drifting it can produce strikes from unexpected lies.',
  'trout-spinnerbait':
    'Trout-sized spinnerbaits—typically single-blade models—are best suited for searching lightly pressured ponds and lakes. The blade\'s flash and water displacement draw Amago and Cherry Salmon from distance. Slow-rolling near bottom in deeper areas tends to produce larger fish.',
  'bluerunner-metal-jig':
    'Metal jigs combine extreme casting distance with high-speed sink rates for targeting pelagics. Rhythmic jerk-and-fall action works both horizontal and vertical planes to trigger chasing strikes from Yellowtail and Amberjack. Choose jig weight at roughly 3x the water depth, sinking to bottom before working a one-pitch retrieve back up.',
  'bluerunner-minnow':
    'Minnows for bluerunner species achieve perfect match-the-hatch imitation of sardines and anchovies. Jerk-and-pause after a long cast combines flash and sudden stops to trigger bites. On surface-feeding blitzes, start the retrieve immediately on splashdown to hook fast-moving Spanish Mackerel and Bluefish.',
  'bluerunner-popper':
    'Popper fishing over a pelagic blitz is the peak of topwater excitement. The cupped face pushes splash and sound that further excite bluerunners already driving bait to the surface, producing explosive surface strikes. Dog-walking with quick jerks and high-speed pauses reduces missed bites.',
  'bluerunner-sinking-pencil':
    'Sinking pencils are a staple for targeting pelagics. Fall-bite patterns are common—let the lure sink through the school\'s depth, then slow-wobble it back up. They are particularly effective along tide lines and current breaks, with bites concentrating during the pause after a jerk.',
  'bluerunner-diving-pencil':
    'Diving pencils are worked with the rod to grab water, producing a unique splash-and-dive action that draws pelagics in. The near-surface swimming is visually exciting and easily flips the feeding switch. A rhythmic rod cadence is the key, with best results at dawn and dusk.',
  'bluerunner-pencilbait':
    'Pencil baits float on the surface, enticing pelagics through walk-the-dog and splash actions. They are ideal for casting into surface blitzes when bait is being pushed up. The interplay of movement and pause becomes the bite trigger. Always confirm the swim action by adjusting hook size and setting before fishing.',
  'bluerunner-vibration':
    'Lipless crankbaits excel when pelagic activity is low or when you need to probe deeper zones. Lift-and-fall or steady retrieves search a wide area, and the strong vibration maintains presence even in dim conditions at dawn and dusk. Varying the countdown to find the cruising depth is the fundamental technique.',
  'bluerunner-spintail':
    'The flash and vibration from a spintail jig\'s rear blade directly trigger the predatory instinct of pelagics. A simple steady retrieve produces ample action, and the blade keeps spinning even on the fall. The stronger the current hitting the blade, the more it turns and the greater the appeal.',
  'bluerunner-metal-vib':
    'Metal vibs sink fast, reaching bottom reliably even in deep water or strong wind. Repeated lift-and-fall thoroughly covers the bottom zone and excels where pelagics are pinning bait against sand flats or reef edges. Maintaining stable operation against the current is the key to building a catch.',
  'bluerunner-worm':
    'Soft plastics for pelagics may seem unconventional, but they have a strong track record on surface blitzes and topwater patterns. Pin-tails and paddle-tails on a fast steady retrieve are devastating during whitebait (Shirasu) patterns. Better hookup rates and reduced throw-offs compared to jigs make them a trump card on pressured waters.',
  'bluerunner-bigbait':
    'Big baits specifically target trophy-class pelagics. Their large silhouette and powerful wobble reach distant fish that ignore other lures, pulling in lunker-sized Yellowtail and Amberjack. When you want to make an impact statement from surf or rocky shore, this is the lure to reach for.',
  'bluerunner-swimbait':
    'Swimbaits use a realistic baitfish silhouette and natural tail action to coax bites from pressured pelagics. They hold high value as a rotation option when jigs and vibs stop working, maintaining presence even on a slow retrieve. Deploying them when the tide slackens can be especially effective.',
  'bluerunner-jighead':
    'A jig head rig offers fine control over the target depth, making it powerful when pelagics are stacked in a specific layer. Adjust weight for countdown depth control and swap worm styles to vary the action. The lighter tackle translates to more direct fights with trophy fish.',
  'hirame-minnow':
    'Minnow fishing for Japanese Flounder is all about tracing the near-bottom zone as long as possible. Start the retrieve just before the lure touches down and maintain a depth of 30–50 cm off the sand. Switching between deep-diving and floating models keeps the lure in the zone even in rough surf.',
  'hirame-metal-jig':
    'Metal jigs bring casting distance and sink speed to Japanese Flounder fishing. From surf or seawall, reach offshore breaks and work the bottom with lift-and-fall. Bites frequently come on the drop, so maintaining tension while reading line movement is the key variable for success.',
  'hirame-worm':
    'Soft plastics are indispensable for slow presentations targeting Japanese Flounder. A shad-tail crawled near bottom swims just above the sand with devastating appeal. In cold water and winter conditions the natural action becomes even more effective, picking up fish that ignore hard baits.',
  'hirame-sinking-pencil':
    'Sinking pencils are most effective when drifted naturally in the surf current for Flounder. Control the sink with a countdown, starting the retrieve just above bottom. Slow wobble provides natural appeal, with bites triggered by the pause after a jerk.',
  'hirame-vibration':
    'Lipless crankbaits for Japanese Flounder excel at alerting distant fish. Cast far, sink quickly to bottom, then maintain depth through lift-and-fall retrieves. Their stable underwater action even in dirty water and wind gives consistent results in rough surf conditions.',
  'hirame-spintail':
    'The blade flash of a spintail jig draws Japanese Flounder from distance. A slow retrieve near bottom keeps the blade spinning, reflecting light even in gentle current. Particularly effective during low-light early mornings and evenings when Flounder patrol the bottom hunting baitfish.',
  'hirame-swimbait':
    'The realistic silhouette and supple tail action of a swimbait is devastating against pressured Japanese Flounder. A valuable rotation option once the sun climbs and pressure increases. Pair with a jig head to adjust weight and run the lure just off bottom for the standard approach.',
  'hirame-bigbait':
    'Big bait fishing for Japanese Flounder is a strategy for selectively drawing out trophy-class fish. Individuals that respond to large profiles tend to be quality size—60 cm and above. Work them slowly near deep surf pockets or harbor run-outs for dramatic chase-and-smash strikes.',
  'rockfish-worm':
    'Soft plastic fishing for rockfish demands reading rock structure and current to present the bait as slowly and naturally as possible. Texas rigs or free rigs with grubs and creature baits fished tight to crevices are the standard approach. Set the hook immediately on any subtle line movement or added weight during the fall.',
  'rockfish-jighead':
    'Jig head rigs are the go-to for light-tackle rock-zone exploration when targeting rockfish. Crawl them down rocky slopes to draw strikes from fish hiding in the gaps. Select the lightest head that still maintains bottom contact in the current, and carefully follow the bottom-touch sensation as you work the rig.',
  'rockfish-metal-jig':
    'Metal jigs are the choice for targeting mid-size and larger rockfish, or for searching deeper, wider areas. Short-pitch jerks and lift-and-fall trigger reaction bites from ambush-oriented rockfish. Tight, repetitive actions from mid-column to bottom thoroughly cover the strike zone.',
  'rockfish-minnow':
    'Targeting rockfish with minnows is ideal along shallow rocky shelves and tidal platforms. Cast tight to cover and twitch to draw strikes from fish actively chasing bait. Choose a short-lipped floating minnow and present it slightly off the bottom with lateral movement rather than hugging the rocks.',
  'rockfish-sinking-pencil':
    'Sinking pencils become an interesting option for rockfish when surface activity is high. A slow-sinking type drifted down draws strikes from suspended fish reacting to the fall. Cast along reef edges and shallow rock zones during a hot bite for a shot at surprisingly large specimens.',
  'mebaru-worm':
    'Worm fishing for Mebaru (Japanese Rockfish) is defined by depth control and fall-speed management. Thread a 1–2 inch pin-tail or grub onto a jig head and let the current carry it down slowly. Bites often come the instant tension is released—reading line changes and subtle weight increases is the key to building numbers.',
  'mebaru-jighead':
    'Lightweight finesse is the weapon of a Mebaru jig head rig. Drifting a worm on a 0.5–1.5 g head through shadow lines and dock-light edges draws bites from lurking fish. Add a float rig to extend range to offshore spots where bigger fish hold and search efficiently.',
  'mebaru-minnow':
    'Minnow fishing for Mebaru centers on tracing a lane just below the surface. A floating minnow on a slow retrieve draws trailing fish that commit the instant it pauses. Especially effective under dock lights at night—start with silhouette-oriented colors visible in the light.',
  'mebaru-sinking-pencil':
    'When using a sinking pencil for Mebaru, picture the lure drifting just below the surface. A slow steady retrieve or free drift presents naturally and fools wary fish. This low-resistance lure is at its best when Mebaru are rising under dock lights chasing bait near the surface.',
  'mebaru-vibration':
    'A small lipless crankbait is the ace up your sleeve when Mebaru ignore jig heads. It excels for probing bottom during daytime sessions or when cooling water pushes fish deeper. A short lift-and-fall triggers reaction bites from fish that respond to movement.',
  'aji-worm':
    'Soft plastic selection for Aji (Horse Mackerel) directly impacts catch rate through material softness and finesse of action. A slim 1–2 inch pin-tail matched to a jig head and drifted on a free fall in the current is the standard. At night, minimize movement and feel for subtle line-tension changes—this sensitive operation is the core of productive Ajing.',
  'aji-jighead':
    'Jig head weight selection governs everything in Ajing. Read current strength and depth, then pick the lightest head that still sinks slowly under tension. To detect fall bites, keep line snug but not taut, managing different depths by counting down from surface to bottom.',
  'aji-metal-jig':
    'Metal jigs efficiently search for roaming schools of Aji. Steady-retrieve through the mid-column while varying depth until you find the response zone, then concentrate there. Micro jigs fished spoon-style also work well for searching tide-line fish at distance during daytime sessions.',
  'aori-ika-egi':
    'Eging (squid-jigging) for Bigfin Reef Squid comes down to managing the jerk rhythm and the following fall time. Autumn Aori-ika aggressively chase the egi, so two-to-three snaps followed by a controlled fall gets the grab. For cautious spring trophy squid, long falls are the ticket. Drifting with the current efficiently covers ground and locates big individuals.',
  'madai-tai-rubber':
    'Tai Rubber (kabura-style jig) fishing for Red Sea Bream starts with selecting the right skirt color and head weight. Vary the steady retrieve speed while re-touching bottom to match the boat\'s drift, searching for the layer where Madai rise to feed. When you feel the tap-tap of an initial bite, maintain speed without changing, and wait for the rod to load fully before setting the hook.',
  'madai-metal-jig':
    'When targeting Red Sea Bream with metal jigs, a slow slide-fall repeated from bottom to mid-water is the fundamental technique. Bites concentrate during the fall, so reacting quickly to line movement and slack is what raises your hookup rate. Silver and gold flash colors are especially effective during bright conditions.',
  'kurodai-worm':
    'Drift-fishing a worm downstream along the bottom is devastatingly effective for Black Sea Bream (Kurodai). A craw-style soft plastic rolled along the sand mimics crustaceans naturally, keeping the lure in the feeding zone for extended periods. Work structure edges meticulously—the majority of bites come during the fall.',
  'kurodai-popper':
    'A popper is the go-to topwater for Black Sea Bream chining in harbors and shallow rivers. The popping sound and surface disturbance trigger the feeding instinct, producing explosive surface strikes. Bites typically come right after the pause, so building a clear move-and-stop rhythm directly translates to more hookups.',
  'tachiuo-metal-jig':
    'Targeting Largehead Hairtail with metal jigs is primarily a boat-based vertical jigging game. Slim-profile jigs maintain an excellent fall posture and achieve deep hooksets. Vary the depth incrementally to pinpoint the school, then trigger reaction bites with short jerks followed by a controlled fall.',
  'tachiuo-worm':
    'Soft plastics for Hairtail (Tachiuo) have proven especially effective from shore. Thread a slim shad-tail or ring-worm on a light jig head and slow-roll through the mid-column to let the Hairtail chase from the side. Metal-armed worm hooks withstand the razor-sharp teeth and dramatically improve hookup rates.',
  'hiramasa-metal-jig':
    'Jigging for Yellowtail Amberjack (Hiramasa) is a battle of endurance and focus. Long-stroke jerks cover a wide depth range from bottom to mid-water, and you must be ready at all times for the decisive fall bite. Assist hook size and configuration are critical—ensuring they track the fish\'s explosive initial run prevents throw-offs.',
  'hiramasa-diving-pencil':
    'Diving pencil fishing for Hiramasa from shore rocks or offshore boats delivers the ultimate surface-game thrill. The large cup grabs water to produce splash on each dive, drawing fish in with repeated dives. Matching rod angle to retrieve rhythm for consistent action is the secret to bringing Hiramasa to the surface.',
  'hiramasa-popper':
    'Speed is everything when throwing poppers at boiling Yellowtail Amberjack. The loud pops and spray attract surrounding fish, and the visual of a surface chase ending in a strike is unmatched in fishing. Work the rod high to make the popper jump on the surface for the standard action.',
  'kampachi-metal-jig':
    'Greater Amberjack (Kampachi) tend to hold near bottom around structure, making bottom-jigging the primary strategy. Sink the jig without hesitation, then work it with quick short-pitch jerks along the reef edge. Keep fall pauses short and trigger reaction bites to exploit Kampachi\'s renowned speed and explosive strikes.',
  'kampachi-diving-pencil':
    'Topwater diving-pencil fishing for Kampachi reaches its zenith over offshore reefs and seamounts. The sight of a fish surging up to hammer a lure swimming just below the surface is pure adrenaline. Because Kampachi make straighter, more powerful runs than Hiramasa, a robust tackle setup is a prerequisite.',
  'tuna-metal-jig':
    'Tuna jigging is the highlight of offshore fishing. High-pitch jerks search from mid-water to bottom, and reading the moment a passing school comes through is paramount. Drift-jigging—letting the jig ride the current naturally—also produces, and following the captain\'s depth calls is the foundation of success.',
  'tuna-diving-pencil':
    'Diving pencil tactics for Tuna are most effective on surface blitzes. Cast into the center of a bird pile, grab water on the retrieve, and work the lure back quickly to trigger a surface strike. Always verify that hook strength and rod butt power can withstand the initial impact before committing to the fight.',
  'tuna-popper':
    'Poppers for Tuna use an oversized cup to simulate panicked bait. Casting distance lets you reach fish from afar; continuous pops mimic fleeing baitfish and draw explosive surface charges. Post-hookup, sufficient drag setting and strong rod work are the non-negotiable requirements for landing the fish.',
  'yellowtail-metal-jig':
    'Shore jigging for Japanese Yellowtail (Buri) is the origin of the pelagic game. Leverage casting distance to hit blitzes and tide lines, then jerk immediately on splashdown and work one-pitch jerks through the column. Reading the run timing and covering ground to find the school is more productive than pounding the same spot.',
  'gt-popper':
    'Popper fishing for Giant Trevally tests both physical stamina and nerve at the highest level. The thunderous report and water column from a massive cup draws GT from dozens of meters away—the surface strike is unrivaled. Continuous popping with sweeping rod strokes builds excitement, with bites typically coming on the pause.',
  'gt-diving-pencil':
    'Diving pencils offer more sub-surface tracking than poppers for GT, producing extended chase sequences. The rod-work-to-retrieve combination grabs water and dives the lure, and once a GT locks on, maintaining pace without slowing is the key to converting the follow into a bite. Rocky shores and outer-reef edges are the prime arenas.',
  'gt-metal-jig':
    'Jigging for Giant Trevally takes place in deep open water and around submerged reef structure. Working a heavy jig with long-stroke jerks is a pure endurance contest, and tackle balance—specifically the ability to absorb a GT\'s violent initial strike—determines the outcome. Detect fall bites instantly, set hard, and stand firm against the fish\'s run toward the reef.',
  'bass-bigbait':
    'This category is about sending big meals after big bass. Big baits use realistic profiles and water displacement to force strikes even on pressured fisheries. When a 200 g+ monster lure rips across the lake surface, every single cast carries meaning.',
  'bass-blade-bait':
    'A vibration-class metal plate shakes at high speed, covering wide swaths with tight wobble. Devastatingly effective for forced bites in winter deep zones and stained water. Lift-and-fall to trigger reaction strikes is the textbook technique.',
  'bass-buzzbait':
    'The surface blowup you\'ll never forget. A buzzbait\'s continuous splashing noise and spray call bass to the top. Running high-speed along mat cover and reed edges delivers the pure essence of topwater bass fishing.',
  'bass-chatterbait':
    'The erratic blade vibration and wave action cut through dirty water without losing presence. The skirt\'s flow combined with the jig head\'s movement creates a compound trigger. This is the power-style trump card that performs from weed edges to open water all season long.',
  'bass-crankbait':
    'The lip grabs water and hammers its designed depth zone with tight wobble. A single crankbait in the box lets you instantly search vast areas. Hard-bottom contact produces irregular deflections—that is exactly where instinctive bass strikes concentrate.',
  'bass-crawler-bait':
    'Wings or arms move slowly, spreading wakes and bubbles across the surface in the ultimate slow game. Under low-light conditions at night or on overcast days, work the surface quietly and big bass will send up a geyser to eat it.',
  'bass-frog':
    'Walk it across the mat, drop it in holes, and get bit. Walking-the-dog over pads while mimicking a real frog brings even deep-cover lunkers crashing to the surface.',
  'bass-i-shape':
    'Almost no action—just existing. A dead-straight retrieve fools spawn-related bass and fish in slow seasonal moods. The gap between its plain appearance and its catch rate makes it a genuine secret weapon.',
  'bass-jointed-bait':
    'The sinuous S-curve from a jointed hinge. Fish-like swimming draws big bass on pure instinct. The slower you retrieve, the more seductive the action becomes—a permanent first-string lure for trophy hunting.',
  'bass-metal-vib':
    'Iron-plate vibration\'s mobility lets you probe from winter deep zones to shallow breaklines without hesitation. High density means long casts, reaching the far bank or a breakline in a single throw.',
  'bass-minnow':
    'Tight wobble and shimmy fall extract bites from bass that ignore everything else. Add a twitch for a darting escape that perfectly replicates fleeing baitfish. A proven pattern for post-spawn bass in particular.',
  'bass-pencilbait':
    'Rod-work driven walk-the-dog is the fundamental action. Subtler splash than a popper pulls bass from a wider area, and a rhythmic cadence is the shortcut to getting bit.',
  'bass-popper':
    'The cupped face spits water with a sharp chug-chug, calling bass from across the flat. Splash and sound simultaneously stimulate vision and hearing. Bites concentrate during the drift pause, so the patience to wait is the real skill.',
  'bass-propbait':
    'A tail propeller spins, generating fine bubbles and surface noise. The nuanced presentation—subtler than a popper—fools pressured bass into committing. Extended-pause twitch-and-hold is the productive cadence.',
  'bass-rubber-jig':
    'The rubber skirt breathes underwater, settling slowly along structure. From football heads to Arky heads, this covers finesse to power fishing—the undisputed king of bottom presentations.',
  'bass-shad':
    'A flapping tail on the most fish-like body form. Retrieve alone produces a seductive swim; paired with a swim jig or weighted hook, it perfectly commands the mid-range. An understated yet deadly soft-bait design.',
  'bass-sinking-pencil':
    'From splashdown it sinks while maintaining a horizontal posture, generating bites on the fall. Lift-and-fall opens up the vertical game unique to sinking hard baits. It sits at the intersection of hard-bait casting distance and soft-bait finesse.',
  'bass-spinnerbait':
    'Blades emit light and vibration simultaneously, announcing presence through stained water and darkness alike. Blade selection changes the approach, and the ability to deflect cover while efficiently covering ground is the reason for enduring popularity.',
  'bass-spintail':
    'A shad-body with a tail spinner produces multi-dimensional action through jerks and falls. The blade\'s reflected flash reaches bass across a wide area, filling the niche between soft plastics and hard baits.',
  'bass-spoon':
    'A simple metal plate flutters through the water, mimicking the glint of baitfish. There are situations where only a spoon will produce. Lift-and-fall for vertical coverage, swimming for horizontal—one plate enables endless presentations. The angler\'s origin lure.',
  'bass-swimbait':
    'A realistic fish silhouette and precision tail action fool the wariest trophy bass. Match the local forage size—gill, shad, or minnow—for perfect match-the-hatch. A dedicated medium-speed finesse lure.',
  'bass-topwater':
    'The moment a bass blows up on the surface is everything. Popper, pencil, or crawler—surface fishing is every bass angler\'s eternal aspiration. Concentrate at dawn and dusk; the calmer the conditions, the more explosive the action.',
  'bass-vibration':
    'Cast and reel—it vibrates automatically, quickly searching a wide range and area. Rattle models excel for reaction bites in stained water; silent types dominate clear conditions. A trusted search bait across all seasons.',
  'bass-worm':
    'If you have a worm, you can fish. Weightless, Texas, drop-shot—the rigging possibilities are infinite, adapting to any condition. Tail action simultaneously triggers appetite and curiosity, and skill translates directly into results.',
  'seabass-chatterbait':
    'The blade\'s vibration punches through waves to reach Japanese Seabass. The action stays stable even in river current, making it deadly on bottom-feeding pressured fish. Heavier models also serve as effective daytime search lures.',
  'seabass-crawler-bait':
    'A crawling surface action drives Japanese Seabass wild on nighttime rivers. When it locks into a worm-hatch (Bachi) pattern, you can witness fish slowly sucking it from behind. Commit to a slow retrieve and trust the lure—patience produces the catch.',
  'seabass-diving-pencil':
    'A fast retrieve after the cast sends the lure diving; adding jerks produces darting depth changes. Indispensable for hitting Seabass boils head-on. The combination of casting distance and diving ability lets you efficiently work expansive surf and river-mouth zones.',
  'seabass-i-shape':
    'Nearly motionless, yet they eat it. The I-shape retrieve introduced finesse to the Japanese Seabass game. Devastatingly effective on pressured urban rivers and in slow winter seas. Bites—often a rise or side-swipe—frequently come the instant the rod stops.',
  'seabass-other':
    'The Japanese Seabass game embraces diverse tactics. Vibrations, jigs, jig-head rigs—expanding your arsenal for the day\'s conditions is what this category is about. Breaking away from standards and matching the fish\'s behavior pattern is what separates catch rates.',
  'seabass-propbait':
    'The subtle sound and micro-bubbles from a spinning prop draw actively feeding Japanese Seabass. Less conspicuous than a popper yet more action-driven than a pencil, it fills the topwater middle ground. A proven producer of nighttime surface bites.',
  'seabass-spinner':
    'An underwater spinning blade scatters light and maintains presence even in current. It functions as a trigger when Seabass are present but won\'t commit under pressure. A steady retrieve alone often produces follows and strikes.',
  'seabass-spinnerbait':
    'Spinnerbaits deliver aggressive vibration and flash for river and surf Seabass. They handle tight approaches around bridge pilings and reef structure, with particularly high reliability in stained-water daytime sessions.',
  'seabass-spoon':
    'Metal flash and a fluttering fall draw reaction strikes from Japanese Seabass. The standard play is searching vast surf and river-mouth areas with a metal spoon, then reaching a distant boil with a single long cast. Stable fishing even in strong wind is a bonus.',
  'seabass-sutte':
    'Sutte-style lures work the bottom with an egi-like action, specializing in Japanese Seabass around submerged structure and tetrapod gaps. The irregular fall posture—different from a jig head—creates a bite trigger and excels on bottom-oriented lethargic Seabass.',
  'seabass-tai-rubber':
    'Adapting Tai Rubber to the Seabass game is an innovative approach. The slow fall and undulating rubber skirt stimulate the feeding instinct, drawing strikes on a simple slow retrieve from bottom to mid-column. A strong pattern during low-activity winter periods.',
  'seabass-topwater':
    'Throwing a topwater into a summer-dawn Seabass boil is an unmatched thrill. On shallow flats and river mouths where Seabass chase Haku and Inakko mullet, they feed on the surface. The explosive strikes and water columns define the pinnacle moment of the Seabass game.',
  'bluerunner-blade-bait':
    'High-speed steady-retrieve iron-plate vibration flips the switch on pelagics. It dials depth from bottom to surface, efficiently searching through Yellowtail and Amberjack schools. One-pitch jerking leverages casting distance and sink speed for pure reaction-bite tactics.',
  'bluerunner-crankbait':
    'When pelagic activity peaks, a crankbait\'s traced depth and wobble can unleash devastating effectiveness. High-season surface cranking produces thrilling water-breaking strikes. Vary retrieve speed to find the sweet spot.',
  'bluerunner-crawler-bait':
    'When bluerunners pin bait on the surface, a crawler bait\'s wake and water noise strike directly at the feeding instinct. The sight of a Yellowtail or Amberjack crashing the surface is an excitement only experienced firsthand.',
  'bluerunner-i-shape':
    'A finesse approach deployed when pelagics won\'t commit. The notion that an I-shape retrieve works on bluerunners has been validated by catch reports, particularly in Hiramasa (Yellowtail Amberjack) games. It functions as a lockout-breaker during tough bites.',
  'bluerunner-jointed-bait':
    'A multi-segmented body traces an S-curve that awakens the hunting instinct of trophy pelagics. It enables selective targeting of lunker Hiramasa and Yellowtail. The wake and silhouette deliver a convincing baitfish imitation.',
  'bluerunner-other':
    'The pelagic game encompasses many approaches. Tungsten jigs, specialty plugs, and unconventional lures that fall outside standard categories often break a stalemate. The more options you carry for varying fields and seasons, the greater your advantage.',
  'bluerunner-propbait':
    'Throw a prop bait splashing into a blitz and pelagics commit without hesitation. In Hiramasa topwater games, the propeller\'s buzzing frequently serves as the bite trigger. The explosive power when bait is being corralled on the surface is overwhelming.',
  'bluerunner-shad':
    'A shad tail\'s realistic swim precisely attacks pelagics keyed in on specific baitfish. Size-matching to anchovy or kibinago silhouettes is critical, and a swim-jig pairing for match-the-hatch fishing is the dominant approach.',
  'bluerunner-spinner':
    'A spinner\'s blade-generated flash and vibration carry broad search power across open water. When Yellowtail schools are running through an area, a high-speed steady retrieve can produce reaction bites in rapid succession.',
  'bluerunner-spoon':
    'Spoons combine extreme casting distance with intense flash, making them the centerpiece of the pelagic surf game. The distance advantage reaches offshore blitzes that other lures cannot, and the posture stays stable even at high speeds. A universal performer for Yellowtail, Amberjack, and Kampachi alike.',
  'bluerunner-sutte':
    'Sutte lures sink deep and are worked back up, matching the vertical movements of pelagics. Effective when large Yellowtail are stacked near bottom. Staying alert for fall bites and setting quickly are the keys to converting strikes.',
  'bluerunner-tai-rubber':
    'Tai Rubber produces on pelagics more often than most anglers expect. The fluttering rubber skirt is devastating against bottom-hugging Yellowtail and Amberjack. Slow-retrieve-to-fall combinations force bites even on high-pressure grounds.',
  'bluerunner-tenya':
    'Pelagics respond to Tenya rigs when bait is holding deep. The shrimp- or baitfish-mimicking silhouette and distinctive fall draw strikes from Yellowtail and Amberjack alike. Varying the jerk pitch and fall duration is the key variable.',
  'bluerunner-topwater':
    'Surface explosion. The moment a Hiramasa rockets into a diving pencil is the zenith of shore fishing. Long casts from rocks or surf followed by high-speed diving action provoke Amberjack attacks. The combative fight that follows is an experience that changes anglers forever.',
  'black-bass-egi':
    'Targeting Largemouth Bass with an egi (squid jig) may look unorthodox, but it is logical when bass are keyed on crawfish around the spawn. Bottom darts and controlled falls draw cautious pre-spawn trophy bass into committing.',
  'black-bass-metal-jig':
    'Metal jigs in the bass arsenal are specialized for high-speed reaction strikes in winter deep water or stained conditions. The erratic fall action flips the switch, and the ability to probe a wide vertical column is the core strength. A genuine go-big-or-go-home wild card.',
  'black-bass-other':
    'Largemouth Bass fishing thrives on creativity beyond conventional categories. From finesse rigs to big baits, this category encompasses boundary-pushing approaches. The ability to adapt flexibly to changing fields and seasons is what drives skill development.',
  'black-bass-spinner':
    'A spinner\'s blade flash and strong wave action simultaneously trigger the aggression and reaction instincts of bass. Slow-rolling along weed edges and cover produces consistent results in stained water and low-light conditions.',
  'black-bass-spoon':
    'A spoon\'s flash and natural flutter provoke bass into feeding. Lift-and-fall for vertical coverage, swimming for horizontal—this simple metal covers a wide depth range with an infinite capacity for creative application.',
  'black-bass-tai-rubber':
    'Adapting Tai Rubber for Largemouth Bass is a technique gaining attention in recent years. The rubber skirt\'s wave action and the head\'s fall speed trigger the predatory instinct, proving effective on deep suspended bass and under tough conditions.',
  'trout-crawler-bait':
    'A crawler bait\'s surface-tearing wave action triggers the predatory instinct of trout. From managed fisheries to mountain streams, a slow surface retrieve produces results, and dropping one in during a dawn rise window delivers explosive surface strikes on Rainbow Trout.',
  'trout-jighead':
    'Jig head rigs for trout offer depth-slicing versatility from bottom to surface as an all-around system. Worm pairings let you freely adjust wave action and silhouette, producing consistent catches even on pressured managed fisheries.',
  'trout-jointed-bait':
    'The seductive S-curve of a jointed body draws out the pursuit instinct of trout. It generates lifelike action even at dead-slow speeds, making it a trump card during cold water and low-activity periods. It also appeals strongly to large Char in mountain streams.',
  'trout-metal-jig':
    'Casting distance and fast sink rates let metal jigs target trout holding on distant breaks and deep structure. Maximize the flash through lift-and-fall to draw aggressive strikes even in low-visibility stained water.',
  'trout-metal-vib':
    'The high-frequency vibration from a metal body hits the trout\'s lateral line directly. Covering a wide speed range from high-speed retrieve to ultra-slow, it serves as a reliable ace for winter bottom fishing and fast-flowing main rivers.',
  'trout-other':
    'Unconventional lures outside the standard categories expand the possibilities of the trout game. Having a deep bench of situational approaches is what creates the edge over other anglers when conditions get tough.',
  'trout-pencilbait':
    'A pencil bait\'s walk-the-dog action maximally stimulates the aggression of trout. Line-slack twitching to produce side-to-side headshakes brings Yamame and large Rainbow Trout crashing through the surface.',
  'trout-popper':
    'The pop and splash of a popper instantly flip the feeding switch of trout. The cupped-face sound simulates a bug hitting the water—the ultimate weapon for drawing Yamame and Amago to the surface in summer mountain streams.',
  'trout-propbait':
    'The shimmering sound and fine ripples from a spinning prop stimulate trout curiosity. The continuous water noise during a slow retrieve is especially effective during active hatches, bringing large Rainbow Trout out without hesitation.',
  'trout-shad':
    'The subtle tail vibration of a shad-body soft plastic delivers otherworldly bite-inducing power against trout. Even in the most severe clear-water conditions it draws bites without spooking, serving as a consistent all-rounder regardless of fish size.',
  'trout-topwater':
    'Explosive strikes on a floating topwater lure are the single greatest thrill of trout fishing. Deploy at dusk during the rise window and large Char or Rainbow Trout will attack with abandon—pure excitement on the water.',
  'trout-worm':
    'A soft-material\'s natural wave action disarms the wariness of pressured trout. Weightless drifting or drop-shot rigs solve lockjaw situations, offering a dependable approach for breaking through stalemates at managed fisheries.',
  'hirame-crawler-bait':
    'A crawler bait\'s wobbling swim action triggers reaction strikes from Japanese Flounder. Carefully tracing the surf break line can bring sand-dwelling ambush predators surging up through the water column.',
  'hirame-other':
    'When jigs and minnows can\'t cover the situation, alternative approaches open new opportunities. A flexible selection eye matched to surf conditions and tidal changes creates the chance to pinpoint Flounder holding spots.',
  'hirame-pencilbait':
    'A pencil bait swimming in an S-curve just below the surface can bring Japanese Flounder off the bottom. Effective when activity is high, and even a dead-slow walk along the wash zone can produce dramatic topwater strikes from Flounder.',
  'hirame-popper':
    'A popper\'s splash and sound stimulate the predatory instinct of Japanese Flounder. Dog-walking through ultra-shallow surf zones and rip-current intersections can bring Flounder chasing bait right up through the surface.',
  'hirame-magochi-jighead':
    'A jig head and worm combination is the ultimate bottom-contact rig for flatfish. Confirm the touchdown, then work lift-and-fall along the sandy bottom to efficiently target both Japanese Flounder and Bartail Flathead.',
  'hirame-magochi-metal-jig':
    'Metal jigs reach distant breaks and deep-water Flounder and Flathead from the surf with long casts. A fast sink secures bottom contact quickly, and slow lift-and-fall extends the time in the strike zone—a proven strategy.',
  'hirame-magochi-minnow':
    'A minnow\'s wobble traced tight to the bottom triggers the feeding response of flatfish. Slow-roll along surf break lines and shelf edges to present strongly to waiting Flounder and Bartail Flathead.',
  'hirame-magochi-sinking-pencil':
    'A sinking pencil with countdown depth control and a dead-slow retrieve offers precision access to bottom-hugging Flounder and Flathead on the surf. The ability to dial in the exact running depth is its core advantage.',
  'hirame-magochi-worm':
    'The subtle wave action of a soft worm stimulates the sensitive lateral line of flatfish. Texas rigs or jig heads minimize snags while a slow bottom retrieve draws committed bites from both Flounder and Bartail Flathead.',
  'kurodai-metal-vib':
    'A high-density metal vib on a steady retrieve draws reaction strikes from Black Sea Bream (Kurodai). Ripping it along cobble beaches and reef edges at speed appeals to the territorial aggression of Chinu for an aggressive approach.',
  'kurodai-minnow':
    'A minnow traced tight along shallow reefs and eelgrass beds draws Black Sea Bream into striking. From slow winter retrieves to fast summer burns, this approach broadly covers conditions and raises the hit rate on Chinu.',
  'kurodai-other':
    'Unconventional lures bring new dimensions to the Black Sea Bream (Chinu) game. Across rivers, tidal flats, and rocky shores, situation-matched approaches open up new possibilities for diverse fields.',
  'kurodai-pencilbait':
    'A pencil bait\'s walk-the-dog action elevates the topwater Kurodai game to its peak. When you hear feeding sounds on a shallow flat, throw the pencil immediately. The explosive surface strike of a Chinu is an unforgettable experience.',
  'kurodai-sinking-pencil':
    'The subtle depth-holding ability of a slow-sinking pencil is the key to cracking pressured Black Sea Bream. Current-assisted drifts and slow presentations along structure force visible Chinu to open their mouths.',
  'kurodai-spoon':
    'A spoon\'s flash and natural swimming action trigger the instinct of Black Sea Bream. Drifting with the tide on a slow retrieve is particularly effective against harbor and surf Chinu.',
  'kurodai-vibration':
    'The strong vibration and flash of a lipless crankbait simultaneously stimulate curiosity and reaction in Black Sea Bream. Bottom bumping and lift-and-fall efficiently search structure-oriented Chinu and draw aggressive bites.',
  'madai-crankbait':
    'A crankbait\'s wobble and diving ability let you directly target the swimming layer of Red Sea Bream. Combining slow-retrieve pauses with movement triggers reaction bites from actively feeding Madai.',
  'madai-minnow':
    'A slim silhouette with sharp wobble-and-roll stimulates the feeding urge of Red Sea Bream. When Tai Rubber draws no response, or when fish are blitzing the surface, a minnow is the ace that produces explosive bites from large Madai.',
  'madai-other':
    'Unconventional lures that fill the gaps when standard Tai Rubber or jigging can\'t adapt to the situation. Reading subtle condition changes—current shifts, temperature breaks—and selecting accordingly is what separates catch rates for Red Sea Bream.',
  'madai-sinking-pencil':
    'A slow-sinking pencil on a steady drift-and-retrieve traces the Red Sea Bream strike zone for an extended distance. The slim profile and natural swim fool even large, cautious Madai—a powerful finesse weapon.',
  'madai-worm':
    'The ultra-natural wave action of a soft worm flips the switch on Red Sea Bream. Jig head or offset-hook rigs cover surface to mid-column, coaxing bites from pressured Madai that refuse everything else.',
  'rockfish-diving-pencil':
    'The violent splash and diving action of a diving pencil triggers the territorial instinct of rockfish. Cast to rocky points and work the action to bring them charging out of their lairs.',
  'rockfish-other':
    'Unique lures that expand the arsenal for rockfish across diverse structure-heavy terrain. When Texas rigs can\'t reach certain crevices or a reaction approach is needed, unconventional presentations deliver.',
  'rockfish-popper':
    'A popper\'s splash triggers the feeding instinct of rockfish. Short-jerk a popper along reef edges and rocky structure to bring Scorpionfish (Kasago) and Grouper (Kijihata) crashing through the surface.',
  'rockfish-spintail':
    'The blade flash and strong wave action of a spintail jig trigger reaction bites from rockfish. Steady retrieves and lift-and-fall around structure cover a wide depth range, with a strong track record on Scorpionfish and Bekkou-zoi.',
  'rockfish-topwater':
    'Topwater rockfishing delivers excitement beyond imagination. Drop a lure along the reef edge and let it struggle on the surface—Kasago and Grouper will surge up from the rocks to hammer it in a thrilling display.',
  'mebaru-jointed-bait':
    'The supple S-curve of a jointed body stimulates the feeding instinct of Mebaru (Japanese Rockfish). Dead-slow retrieves around dock lights and seaweed beds draw fish that track the lure patiently before committing with confidence—a high finesse-bite lure.',
  'mebaru-metal-jig':
    'Small metal jigs use fast sink and flash to trigger reaction strikes from Mebaru. From dock lights on breakwaters to deep rocky zones, the casting distance lets you quickly cover offshore-roaming schools.',
  'mebaru-other':
    'Approaches outside the standard Mebaring playbook crack the code on pressured fish. Float rigs, plugging, and varied techniques provide the breakthrough to put bites on fish that have refused everything conventional.',
  'mebaru-pencilbait':
    'Watching Mebaru respond to a pencil bait swimming just below the surface on a dead-slow retrieve is a high-skill game. Presenting the silhouette at the eye level of dock-light Mebaru focused on bait delivers explosive topwater strikes.',
  'mebaru-spintail':
    'The blade flash of a spintail jig strongly appeals to the vision of Mebaru. Even a simple steady retrieve produces a natural fluttering swim that efficiently picks up surface-to-midwater Mebaru—a versatile all-rounder.',
  'aji-jointed-bait':
    'The soft movement of a jointed bait naturally triggers the feeding response of Aji (Horse Mackerel). Dead-slow surface retrieves under dock lights draw fish that detect the tail\'s subtle vibration and commit with a suction bite. Upsizing potential is a bonus.',
  'aji-minnow':
    'A slim-profiled minnow syncs with the baitfish pattern of Aji. Countdown to the school\'s depth, then slow-retrieve to systematically pick fish from the edge of the group—outstanding practical catch performance.',
  'aji-other':
    'Unconventional lures that come into their own when standard Ajing rigs hit a wall. The judgment to match current, depth, and fish activity to the optimal approach is what unlocks both numbers and quality.',
  'aji-sinking-pencil':
    'A sinking pencil with freeform countdown depth control directly targets the swimming layer of Aji. Dead-slow steady retrieves minimize wave action, drawing natural bites even from wary dock-light fish in clear water.',
  'aji-spintail':
    'The blade flash of a micro spintail jig locks onto the vision of Aji. A simple steady retrieve produces consistent results, earning deep trust as a reliable option for long-distance casting in wind and deep-zone Aji targeting.',
  'aji-vibration':
    'The strong vibration of a lipless crankbait stimulates the lateral line of Aji and triggers reaction bites. Even in fast current or when Aji drop to depth, it quickly identifies the holding zone for efficient run-and-gun fishing.',
  'aori-ika-sutte':
    'The color palette and posture changes of a Sutte simultaneously stimulate the curiosity and predatory instinct of Bigfin Reef Squid. Glow and luminous materials are devastatingly effective for night and boat-based eging. Combining as a dropper with a standard egi is a proven setup that boosts catch rates significantly.',
  'aori-ika-worm':
    'Soft-material Tip-Run egi and worms appeal to the delicate tactile senses of Bigfin Reef Squid. Dead-fall and slow-jerk presentations in current deliver extremely high bite-inducing power against pressured Aori-ika.',
  'hiramasa-minnow':
    'A realistic baitfish silhouette and wobbling action stimulate the predatory instinct of cruising Yellowtail Amberjack (Hiramasa). Work them tight along rocky white-water zones and tide lines for explosive strikes.',
  'hiramasa-other':
    'Lures that expand the Hiramasa arsenal. Matching the type to conditions opens the door to bites when standard approaches have been shut out.',
  'hiramasa-pencilbait':
    'If you want to feel a Hiramasa blow up on the surface, pencil bait is the only answer. Walk it side to side and watch fish compete for the strike in the heart of the blitz, sending up water columns. This is the essence of the pelagic topwater game.',
  'hiramasa-sinking-pencil':
    'A sinking pencil combines casting distance with versatile action for a cornerstone role in the Hiramasa game. From steady retrieve to twitch, it handles multiple techniques and efficiently searches a wide depth range from surface to mid-column.',
  'kampachi-minnow':
    'Greater Amberjack (Kampachi) frequently show reflexive strikes on minnows. Speed-cranking and jerking create the windows that provoke reaction bites. The drag-screaming fight that follows is addictive.',
  'kampachi-other':
    'Kampachi fishing demands condition-reading lure selection. Approaches that perform in low-activity windows and finicky bites increase the probability of experiencing that famously powerful fight.',
  'kampachi-popper':
    'For explosive surface-strike fishing, the popper reigns supreme. The cupped face sends up spray and sound that trigger Kampachi\'s attack instinct, producing violent strikes. The exhilaration of the pelagic topwater game is second to none.',
  'kampachi-sinking-pencil':
    'A sinking pencil that reads the current and searches wide areas is effective on cruising Greater Amberjack. High castability reaches offshore tide lines, turning encounters with trophy-class fish beyond shore range into reality.',
  'tuna-other':
    'Tuna demand casting distance and tackle strength beyond the ordinary. Unconventional approaches that attract distant blitz fish and overpower the sheer force of the fight are what this category delivers.',
  'tuna-pencilbait':
    'Chasing a topwater tuna bite on the open ocean. Cast a pencil bait to distance and work it on the surface to flip the switch on cruising tuna. The piercing strike and titanic fight are the pinnacle of the offshore game.',
  'tuna-sinking-pencil':
    'When the blitz is distant or fish are focused on the mid-column, a sinking pencil comes into its own. Countdown to the cruising layer and work the action at the right depth to create reliable bite opportunities on Tuna.',
  'yellowtail-minnow':
    'Japanese Yellowtail (Buri) readily show reaction strikes to minnows. Jerking and speed-cranking create the illusion of panicking bait to trigger chases. The winter Buri season produces especially strong responses, with a proven track record for trophy-class fish.',
  'yellowtail-other':
    'A diverse lure selection that broadens the Yellowtail game. Water temperature, current, and bait species change the optimal approach. Adapting selection to conditions maximizes encounter probability with Buri.',
  'yellowtail-pencilbait':
    'Yellowtail topwater fishing is pure adrenaline. Walk a pencil bait on the surface and watch the school compete for the strike. The instant effectiveness on surface blitzes makes it a staple of the pelagic topwater arsenal.',
  'yellowtail-sinking-pencil':
    'When Yellowtail are cruising the mid-column or when blitzes are far offshore, a sinking pencil is the reliable choice. Leverage casting distance to search wide, adjusting retrieve speed to control depth as you work through the school.',
  'gt-pencilbait':
    'The pencil bait is the protagonist of the GT game. Cast a 100 mm+ plug to distance and drive it with powerful rod strokes. The sight of a Giant Trevally plowing through the whitewash to engulf it is a once-in-a-lifetime moment of tropical game fishing.',
  'magochi-bigbait':
    'To selectively target trophy Bartail Flathead (Magochi), a big bait\'s presence creates overwhelming separation. A realistic swimming action worked near bottom draws the largest individuals and elevates the scale of the flatfish game.',
  'magochi-metal-jig':
    'Metal jig tactics for Bartail Flathead center on one-pitch jerks after touching bottom. Re-establishing bottom contact and working a slow presentation puts the jig directly in front of sand-dwelling Magochi. Ideal for efficiently searching deep surf and harbor zones.',
  'magochi-minnow':
    'Bartail Flathead bite when a minnow is traced just above the bottom. A lipped floating minnow retrieved slowly with intermittent bottom contact kicks up sand clouds that draw Magochi in. A classic surf-game technique.',
  'magochi-pencilbait':
    'When Bartail Flathead turn their attention to the surface, a pencil-bait topwater game becomes viable. The ferocious topwater strike from a flatfish defies expectations and delivers pure game-fishing excitement.',
  'magochi-swimbait':
    'A swimbait\'s realistic swimming action excels during Magochi\'s selective feeding periods. The subtle tail vibration draws Flathead holding in the bottom feeding zone.',
  'magochi-worm':
    'Worm tactics for Bartail Flathead center on the jig head rig. Drag the bottom with occasional shakes to mimic goby and sandworm movement. The high bite-inducing power produces stable catches even on pressured flats.',
  'kasago-jighead':
    'Scorpionfish (Kasago) aggressively bite jig head rigs. Drop the rig into tetrapod gaps and along rock edges, then crawl it slowly across the bottom for rapid-fire bites. A light-game staple enjoyed by beginners and experts alike.',
  'kasago-vibration':
    'The tight action of a lipless crankbait triggers Kasago\'s feeding instinct. Lift-and-fall around reefs and structure efficiently locates bottom-dwelling Scorpionfish.',
  'kasago-worm':
    'Soft plastics are one of the most reliable lures in the Kasago angler\'s arsenal. Shrimp or sandworm profiles on a Texas rig or drop-shot deliver consistent bites when punched into rocky crevices.',
  'hata-metal-jig':
    'Grouper (Hata) respond strongly to the fall of a metal jig. Mixing in slack-line jerks near the bottom draws explosive bites from reef-hugging fish. Metal jigs are indispensable for deep rockfish territory.',
  'hata-worm':
    'Grouper species respond exceptionally well to the natural movement of soft plastics. Texas rigs or leaderless drop-shots delivered into rock pockets and fished slowly near bottom are the proven standard approach.',
  'catfish-topwater':
    'Topwater catfish fishing erupts on nighttime rivers. The thunderous surface strike as a catfish engulfs the lure is instantly addictive. Poppers and noisy surface lures worked with audible splashing are the standard tactic.',
  'snakehead-frog':
    'The frog is the undisputed star of the Snakehead game. Slide it across heavy cover and wait for the explosive surface strike as it drops into an opening. A thrilling game-fishing pursuit targeting trophy fish buried under the thickest vegetation.',
  'sweetfish-minnow':
    'Lure fishing for Ayu (Sweetfish) centers on a minnow-based approach mimicking traditional friend-fishing. A minnow imitating a live Ayu drifted through the current triggers territorial attack-bites from wild fish. The clarity of mountain streams and the fight of Ayu combine for a unique experience.',
  'ayu-minnow':
    'Ayu minnows are the cornerstone of lure-based Ayu fishing that exploits their territorial behavior. A silhouette nearly identical to a live decoy fish swims along the streambed to provoke territorial strikes from wild Ayu. Ideal for game fishing in crystal-clear mountain streams.',
  'cuttlefish-egi':
    'Eging for Cuttlefish is a slow-style shallow-water game. No aggressive snapping is needed—simply drag the egi along the bottom slowly, and Cuttlefish wrap onto it. An excellent entry point into the eging world.',
  'squid-egi':
    'Eging uses egi (shrimp/baitfish-mimicking jigs) to attract squid. The combination of snapping jerks and controlled falls draws interest, with the grab typically coming during the sink. Riding the fall bite is the core thrill.',
  'squid-other':
    'A fresh approach to squid fishing beyond standard egi and sutte. Diverse rigs and techniques offer a distinctly different angle of attack, opening new possibilities for targeting squid on pressured grounds.',
  'squid-sutte':
    'Sutte lures strongly stimulate squid\'s vision and lateral line. Glow and luminescent materials are devastatingly effective for night and boat-based fishing. Combining with an egi as a dropper rig is a proven configuration that significantly boosts the catch.',
  'yari-ika-sutte':
    'Spear Squid (Yari-ika) respond well to sutte, with boat-based sutte fishing being the mainstream approach. Multi-dropper rigs make multiple-hookup catches routine. From winter through spring spawning season, casting from shore also becomes viable.',
  'kensaki-ika-sutte':
    'Swordtip Squid (Kensaki-ika) react quickly to sutte, producing satisfying reaction bites on active jigging cadences. Targeting light-attracted schools from nighttime breakwaters or offshore boats offers strong potential for big hauls.',
  'octopus-egi':
    'Octopus egi are purpose-designed squid-jig-style lures with rubber tentacles and curly tails that trigger the octopus\'s wrapping instinct. A slow bottom drag with intermittent shakes is all it takes, and the snag-resistant design makes fishing reef zones far easier.',
  'octopus-other':
    'Octopus fishing demands specialized rigs and strategies. Non-egi octopus lures and setups target large individuals around reefs and wave-breaker blocks. Getting a solid wrap and recovering quickly is the core skill of octopus fishing.',
  'octopus-worm':
    'Soft plastic rigs are a reliable method for targeting octopus. The soft material texture creates minimal alarm, buying extra wrapping time. Texas rigs or bullet-sinker combos methodically work rock structure for precise presentations.',
  'saltwater-sutte':
    'Saltwater sutte fishing produces best around nighttime dock lights and harbor zones. Glow and luminescent sutte materials powerfully attract squid species, enabling efficient numbers-fishing on float rigs or boat drifts.',
  'saltwater-tai-rubber':
    'Tai Rubber is a cornerstone saltwater lure. Despite its simple head-and-skirt design, a steady-speed retrieve triggers the predatory instinct of fish. Its versatility across Red Sea Bream and numerous other species is a major draw.',
  'saltwater-worm':
    'Soft plastics are indispensable in the saltwater game. Their natural action breaks through slow-bite conditions and draws committed strikes in situations where hard baits struggle to reach.',
  'offshore-diving-pencil':
    'Diving pencils are the standard lure for offshore casting games. The rod-worked diving action generates a distinctive wave pattern that draws pelagics from a wide radius. Purpose-built for topwater encounters with large migratory species.',
  'offshore-metal-jig':
    'Offshore metal jigs search every depth from bottom to surface with total freedom. One-pitch jerking on the way up, with bites taken on the fall—the jigging fundamental. They accommodate everything from high-speed to slow-pitch styles.',
  'offshore-pencilbait':
    'Pencil baits command unrivaled presence in the offshore casting game. Long casts toward bird piles and blitzes, powered by vigorous walk-the-dog action, call trophy pelagics to the surface. The headliner of the open-water big game.',
  'mahi-mahi-diving-pencil':
    'Mahi-Mahi (Dorado) show flashy strikes on diving pencils. Cast along tide lines and work the lure sub-surface with erratic action to draw color-blazing Mahi competing for the bite.',
  'mahi-mahi-minnow':
    'Mahi-Mahi respond aggressively to a minnow\'s lip-driven wobble. Speed-cranking and jerking replicate panicking bait, delivering the thrill of acrobatic Mahi blasting through the blue surface.',
  'mahi-mahi-popper':
    'Mahi-Mahi popper fishing delivers non-stop visual excitement. Work the cup to produce sound and spray, and gold-green Mahi will charge boldly. The full-throttle experience of offshore topwater fishing.',
  'tachiuo-other':
    'Largehead Hairtail (Tachiuo) can be targeted with everything from bait-wrapped Tenya to casting lures. Specialized tackle that handles the razor-sharp teeth and unique bite pattern makes the sight of a silver ribbon dancing across the surface an addictive experience.',
  'tachiuo-tenya':
    'Tenya holds an unshakable position in boat-based Hairtail (Tachiuo) fishing. Work the bait-wrapped tenya with fall and lift movements to ride the characteristic upward-feed bite. The definitive style of boat Tachiuo fishing.',
  'aji-pencilbait':
    'A pencil bait\'s sub-surface walk-the-dog action makes topwater Aji (Horse Mackerel) fishing for trophy-size fish a reality. Match the feeding depth of dock-light Aji with a slow retrieve to experience the thrill of plug-based Ajing.',
  'aji-metal-vib':
    'A metal vib\'s high-density body delivers casting distance even into a headwind, excelling in daytime deep-zone Aji fishing. Lift-and-fall quickly pinpoints the school\'s depth for efficient numbers-building.',
  'seabass-frog':
    'A frog\'s subtle splashdown and slow crawl draw Japanese Seabass from under cover. Navigate weed zones and moored-boat shade snag-free, and the surface explosion on the bite is extraordinary.',
  'seabass-rubber-jig':
    'The skirt-wave action and slow fall of a rubber jig target bottom-holding Japanese Seabass. Precisely dropping along bridge-piling bases and submerged rocks pulls out resident fish that ignore conventional hard baits.',
  'kurodai-crankbait':
    'A crankbait\'s wide wobble triggers the curiosity of Black Sea Bream. Deflecting the lip off shallow cobble and riprap generates reaction bites—an approach gaining traction as a fresh angle in the Chinu game.',
  'chinu-kurodai-popper':
    'Poppers are essential for topwater Black Sea Bream (Chinu) action. Popping across tidal flats and shallow areas produces dramatic surface blowups from Chinu. Dawn and dusk are the prime windows.',
  'madai-jighead':
    'A jig head and worm rig offers a light-tackle approach to Red Sea Bream. When Tai Rubber draws blanks on lethargic fish, a slow fall with subtle shakes coaxes the gentle suction bite.',
  'hirame-jighead':
    'A jig head rig delivers the highest-precision bottom approach for Japanese Flounder. Lift-and-fall after touching down puts the worm in the strike zone of sand-dwelling fish, and the classic feed-up bite on the fall is securely hooked.',
  'hirame-spinnerbait':
    'A spinnerbait\'s blade flash and skirt wave catch surf-zone Flounder from a wide area. Slow-rolling near bottom, the flashing blade flips the feeding switch on sand-buried Japanese Flounder.',
  'catfish-crawler-bait':
    'A crawler bait\'s surface-crawling action and distinctive water noise drive Catfish into a frenzy. Slow-retrieve through nighttime rivers and irrigation channels for thunderous topwater strikes and the full Catfish-game experience.',
  'bluerunner-all-pencilbait':
    'Walk-the-dog pencil baits are the single strongest topwater choice for pelagics across the board. Yellowtail, Amberjack, and Kampachi crashing the surface create memories etched deep in every angler\'s mind. Instant effectiveness on surface blitzes is overwhelming.',
  'bluerunner-all-sinking-pencil':
    'Sinking pencils offer broad versatility for targeting pelagics in general. Countdown to depth and pick off species from Yellowtail to Kampachi. Casting distance and action freedom make this a mainstay of the shore-jig game.',
  'bluerunner-all-metal-jig':
    'Metal jigs are the backbone of the pelagic game. From shore to offshore, one-pitch and slow-pitch jerks cut across Yellowtail, Amberjack, and Kampachi. Weight and silhouette selection dictate the day\'s results.',
  'bluerunner-all-blade-bait':
    'The high-speed vibration and flash of blade baits draw reaction strikes from pelagics across species. A simple steady retrieve efficiently searches wide areas, and when a school is located, chain hookups are far from rare.',
  'bluerunner-all-diving-pencil':
    'Diving pencils are the showpiece of rock and surf casting for pelagics. Rod-worked sub-surface dives directly target the predatory instinct of every bluerunner species from Yellowtail to Amberjack.',
  'rockfish-all-metal-jig':
    'Metal jigs are ideal for deep-zone rockfish coverage. Lift-and-fall from rocky shores or boats efficiently targets Scorpionfish, Greenling, and Grouper. The fluttering flash on the fall is the primary bite trigger.',
  'rockfish-all-jighead':
    'Jig head rigs are the standard rockfish tactic. Punching a worm into tetrapod gaps and reef zones for a slow bottom crawl draws reliable bites from Scorpionfish and Greenling. Fine-tuning head weight is the key variable.',
  'trout-all-crankbait':
    'Crankbaits are the all-around performer from managed fisheries to native-trout streams. Lip angle dials in the depth, and tight wobble coaxes bites from even the most reluctant trout.',
  'trout-all-minnow':
    'Minnows are the foundational trout-fishing lure. From managed-pond Rainbows to mountain-stream Char, the classic twitch-and-pause action works universally—an effective approach even on pressured fish.',
  'trout-all-jighead':
    'Jig head rigs cover trout fishing from bottom probing to swimming presentations. From dead-slow managed-fishery sessions to fast-water drifts, head-weight selection broadens the range of approach.',
  'trout-all-other':
    'Spoons, spinners, and other lures outside standard categories expand the trout-fishing toolkit. The unconventional approach that becomes the deciding factor under tough conditions is often in this group.',
  'trout-swimbait':
    'A swimbait\'s realistic profile and tail action stimulate the feeding instinct of trophy trout. Slow retrieves on lakes and main rivers are the foundation, matching forage like Wakasagi (pond smelt) and Oikawa (pale chub) for a precise match-the-hatch approach.',
  'squid-all-egi':
    'Egi are the universal squid lure, covering everything from Bigfin Reef Squid to Spear Squid. Snap-and-fall combinations adapt to each species\' behavior, with size and color matched to season and region determining the catch.',
  'crappie-worm':
    'Soft plastics are the most versatile lure in Crappie fishing. Small curly-tails or grubs on a jig head fished with a slow fall efficiently build numbers when schools are located.',
  'crappie-jighead':
    'Jig head rigs are the go-to for Crappie. A lightweight head with a micro worm dropped slowly into brush piles and submerged timber produces chain bites from schooling fish.',
  'crappie-swimbait':
    'A swimbait\'s realistic shad-tail action triggers feeding responses from slab-sized Crappie. Slow-swimming along breaklines and structure edges opens the door to trophy encounters.',
  'crappie-rubber-jig':
    'A rubber jig\'s skirt wave stimulates Crappie curiosity. Tight drops into brush piles and weed edges on a slow fall draw concentrated bites from quality Crappie.',
  'crappie-crankbait':
    'Trolling or casting crankbaits efficiently searches wide areas for Crappie. For fall and winter deep-holding fish, a long-lipped model that reaches the right depth is the key.',
  'crappie-minnow':
    'A minnow\'s tight wobble matches the Crappie baitfish pattern. Slow retrieves around shallow brush piles draw bites from suspended Crappie schools.',
  'redfish-worm':
    'Soft plastics are the standard Redfish approach. Shad-tails or paddle-tails on a jig head worked methodically along flats and marsh shorelines produce reliable bites.',
  'redfish-jighead':
    'Jig head rigs are ideal for sight-fishing Redfish. Cast ahead of a tailing fish on a shallow flat and crawl it along the bottom for an immediate response.',
  'redfish-swimbait':
    'A swimbait\'s realistic baitfish action triggers the predatory instinct of bull Redfish. Slow retrieves along marsh edges and flats deliver powerful strikes and brutal fights.',
  'redfish-spinnerbait':
    'A spinnerbait\'s blade flash and skirt wave cut through muddy water to reach Redfish. Slow-rolling along marsh shorelines catches fish across a wide area.',
  'redfish-topwater':
    'Topwater Redfish fishing reaches the peak of visual excitement. Popper or walk-the-dog presentations to fish chasing bait on shallow flats produce explosive surface strikes.',
  'redfish-minnow':
    'Minnows are the foundation of a match-the-hatch Redfish strategy. Twitch-and-pause along shorelines and dock structures produces chain reaction bites.',
  'redfish-jerkbait':
    'A jerkbait\'s darting action triggers reaction strikes from Redfish. Jerk-and-pause on clear-water flats draws committed bites from trailing fish.',
  'snook-worm':
    'Soft plastics are the most trusted Snook lure. Drop a jig head rig into mangrove roots and dock pilings with a slow presentation, and Snook will charge out of cover to strike.',
  'snook-swimbait':
    'A swimbait\'s realistic swim flips the feed switch on trophy Snook. Match mullet or pilchard size and work inlet zones and beachfronts for the standard approach.',
  'snook-rubber-jig':
    'Rubber jigs are ideal for Snook structure fishing. Flip into dock pilings and seawall edges to draw powerful bites from cover-holding trophy Snook.',
  'snook-topwater':
    'Topwater Snook strikes carry explosive force. Pre-dawn and sunset sessions with walk-the-dog or popper presentations deliver the signature aggressive surface blow-ups Snook are known for.',
  'snook-minnow':
    'A minnow\'s tight action is effective around mangrove-oriented Snook. Twitch-and-pause replicating baitfish movement precisely targets Snook ambush points.',
  'snook-spinnerbait':
    'A spinnerbait\'s blade flash draws Snook from mangrove and marsh cover. The ability to search wide areas while deflecting structure makes it especially devastating in low-light conditions.',
  'snook-jerkbait':
    'A jerkbait\'s erratic dart triggers Snook reaction strikes. Jerk-and-pause on clear-water flats and around inlet zones draws aggressive attacks from holding fish.',
  'seatrout-worm':
    'Soft plastics deliver consistent Seatrout catches regardless of season. A jig head slowly worked across grass flats and sand bars produces chain hookups from schooling fish.',
  'seatrout-swimbait':
    'A swimbait\'s realistic baitfish action directly targets the Seatrout feeding zone. Slow retrieves around grass flats can produce encounters with "gator trout"—the largest trophy-class individuals.',
  'seatrout-topwater':
    'Topwater Seatrout fishing peaks on dawn sessions over shallow flats. Surface blow-ups on walk-the-dog and popper presentations are the essence of inshore game fishing.',
  'seatrout-jerkbait':
    'A jerkbait\'s sub-surface darting action triggers reaction bites from Seatrout. Jerk-and-pause combinations over clear-water grass flats are especially effective.',
  'walleye-crankbait':
    'Crankbaits are the primary weapon in Walleye fishing. Trolling covers expansive areas while lip depth matches the suspended zone of Walleye—the strategic depth match determines the day\'s catch.',
  'walleye-worm':
    'Worm rigs excel in slow-presentation Walleye fishing. A bottom-dragging live-bait-rig feel lets you detect the characteristically delicate Walleye bite.',
  'walleye-swimbait':
    'A swimbait\'s realistic action matches the selective feeding pattern of Walleye. Slow retrieves around deep breaks and humps methodically target trophy-class fish.',
  'walleye-minnow':
    'A minnow\'s wobble-and-roll action directly hits the Walleye feeding zone. Twitch-and-pause mimics a wounded baitfish to trigger reaction strikes.',
  'walleye-vibration':
    'The strong vibration of a lipless crankbait stimulates the Walleye\'s lateral line. Deep lift-and-fall and bottom bumping efficiently trigger reaction bites from lethargic fish.',
  'walleye-jighead':
    'Jig head rigs are the fundamental Walleye technique. Bounce a minnow or worm combination across rocky and gravel bottom and Walleye will reliably commit.',
  'walleye-rubber-jig':
    'A rubber jig\'s slow fall and skirt wave match the bottom-feeding behavior of Walleye. Methodical fishing around rocky bottom and brush piles precisely locates the zones where large individuals hold.',
  'striped-bass-worm':
    'Soft plastics excel for a finesse approach to Striped Bass. A jig head or drop-shot crawled slowly along the bottom draws bites even on heavily pressured waters.',
  'striped-bass-swimbait':
    'A swimbait\'s large silhouette and realistic tail action awaken the predatory instinct of trophy Striped Bass. Heavy models fished slowly through reservoir and river deep zones are the standard approach.',
  'striped-bass-rubber-jig':
    'Rubber jigs are ideal for Striped Bass structure fishing. Flipping into dam intakes and bridge pilings targets cover-hugging trophy fish with powerful bite potential.',
  'pike-worm':
    'Pike aggressively attack large-profile worm rigs with jerkbait-style presentations. Slow-working weed edges and lily-pad zones draws ferocious charges from ambush-oriented Pike.',
  'pike-swimbait':
    'A swimbait\'s large silhouette maximally stimulates the predatory instinct of Pike. Slow-retrieving across weed flats produces the dramatic subsurface surges Pike are famous for.',
  'pike-frog':
    'Frogs are the top choice for Pike weed-mat fishing. Slide across lily pads and pause on open pockets for explosive surface strikes that shatter the calm.',
  'pike-crankbait':
    'A crankbait\'s wide wobble simultaneously stimulates the vision and lateral line of Pike. Fast retrieves along weed edges and rock piles produce rapid-fire reaction strikes.',
  'panfish-worm':
    'Soft plastics are the most reliable lure for Panfish (Bluegill, Sunfish) across the board. Micro-sized grubs and worms on light jig heads fished with finesse deliver numbers-fishing fun.',
  'panfish-jighead':
    'Jig head rigs offer pinpoint accuracy for Panfish. Drop a micro jig into brush piles where Bluegill and Crappie school for chain bites.',
  'panfish-swimbait':
    'Micro swimbaits with realistic tail action selectively target trophy Panfish. Slow retrieves along breaklines and weed edges open the door to slab Bluegill.',
  'panfish-rubber-jig':
    'Micro rubber jigs draw Panfish with their skirt wave action. Slow-fall presentations around brush piles and dock pilings concentrate bites from quality Bluegill and Sunfish.',
  'perch-worm':
    'Soft plastics are the standard Perch lure. Micro curly-tails or grubs on a drop-shot rig efficiently build numbers from schooling Perch.',
  'perch-swimbait':
    'A swimbait\'s realistic action matches the Perch feeding pattern. Slow retrieves along rocky bottom and weed edges draw quality Perch competing for the bite.',
  'perch-crankbait':
    'A crankbait\'s vibration and flash gather Perch from across a wide area. Tight traces along rocky shorelines and break points efficiently produce bites from schooling fish.',
  'perch-spinnerbait':
    'A spinnerbait\'s blade flash strongly appeals to the vision of Perch. Slow-rolling along weed edges and drop-offs, the moment you locate a school, chain hookups become the expectation.',
  'tachiuo-lure-accessory':
    'Accessories like assist hooks, blades, and glow sticks significantly impact catch rates in Largehead Hairtail (Tachiuo) fishing. Wire leaders and tuning components designed for razor-sharp teeth ensure reliable hooksets and safe landings.',
  'aji-shad':
    'A shad plug\'s tight wobble matches the micro-bait pattern of Aji (Horse Mackerel). Dead-slow retrieves through the surface layer under dock lights produce chain bites from plankton-feeding Aji schools.',
  'mebaru-shad':
    'A shad plug\'s subtle vibration triggers the feeding instinct of Mebaru (Japanese Rockfish). Slow retrieves along the shadow line of dock lights deliver precise finesse bites in the plugging Mebaru game. Especially effective in clear water.',
  'crappie-spinnerbait':
    'A spinnerbait\'s blade flash draws Crappie from a wide area in stained water. Slow-rolling around brush piles produces chain bites from schooling fish.',
};
