// src/data/ranking-descriptions-en.ts
// English editorial descriptions for ranking pages
// Key: {fish_slug}-{type_slug} (e.g. seabass-minnow)
// Translated from ranking-descriptions.ts (Japanese)
export const rankingDescriptionsEn: Record<string, string> = {
  'seabass-minnow':
    'When targeting seabass in rivers and tidal flats, minnows offer the best baitfish imitation. Drifting them just below the surface and letting them roll in current seams triggers aggressive strikes. Choose sizes between 90-120mm, matching the prevailing forage.',
  'seabass-vibration':
    'Vibration lures cover a wide range from bottom to mid-water with excellent casting efficiency. During the aggressive fall feeding frenzy, fast retrieves trigger reaction strikes, while dead-slow winter presentations keep a tight wobble near the bottom. They also excel around bridge pilings in light-shadow transitions.',
  'seabass-sinking-pencil':
    'Sinking pencils shine when drifted or slow-retrieved. Letting the current carry them in an S-shaped trajectory faithfully replicates a struggling baitfish. Essential for trophy seabass in surf and river mouths, they also produce well around streetlights during night sessions.',
  'seabass-metal-vib':
    'Metal vibes, also known as blade baits, leverage exceptional casting distance and fast sink rates. Working the bottom with a lift-and-fall cadence sends vibrations that attract seabass from a wide area. They coax bites even during low-activity winter conditions, with hit rates spiking during baitfish migration periods in rivers.',
  'seabass-pencilbait':
    'The walking-the-dog action of a pencil bait directly targets the seabass predatory instinct. Working it side-to-side on the surface and pausing often triggers strikes at the moment it stops. Indispensable for fall mullet patterns and dawn surface blitzes, it delivers the most visually thrilling topwater experience.',
  'seabass-popper':
    'A popper\'s explosive sound can pull seabass all the way to the surface. The cupping action pushes water to create noise and splash that reaches fish from considerable distance. When sardines or gizzard shad are being herded to the surface, popper-based topwater tactics are overwhelmingly effective.',
  'seabass-metal-jig':
    'For seabass from surf and rocky shores, metal jig casting distance is the deciding factor. On shallow surf, skipping a slow-pitch jig across the surface works well, while river mouths call for vertical lift-and-fall presentations. In mixed pelagic zones, 30-50g jigs offer the best versatility.',
  'seabass-spintail':
    'Spintail lures combine blade flash with the supple movement of a soft body. They stimulate both the seabass\'s vision and lateral line, making them particularly effective during low-light conditions at dawn and dusk. A slow retrieve with a subtle tail vibration also produces strikes on the fall.',
  'seabass-bigbait':
    'Big baits come into their own during gizzard shad and mullet seasons. Their weight limits casting range, but their sheer presence excels at drawing trophy-class fish at close quarters. The wobbling generated by jointed segments displaces serious water, pulling in seabass over 90cm.',
  'seabass-worm':
    'Soft plastics offer the most persistent presentation for inactive seabass. Dead-slow-retrieved shad tails produce bites through tail micro-vibrations alone. Slow-rolling and dragging along the bottom near structure serve as the ace up your sleeve when hardbaits fail to draw a response.',
  'seabass-jighead':
    'Jighead rigs deliver pinpoint accuracy when targeting seabass in specific zones. Selecting the right head weight for the depth and target range is critical, with 1-10g being the standard range. Swimming and lift-and-fall techniques in current allow precise timing of the strike window.',
  'seabass-blade-bait':
    'Thin metal bodies generate distinctive vibration and flash. They produce stable vibration across both fast and slow retrieves, delivering year-round versatility. For working shade zones around bridge pilings and tetrapods, vertical lift-and-fall presentations draw fish up from the bottom.',
  'seabass-shad':
    'Shad plugs excel with their compact silhouette that mimics juvenile mullet and mysid shrimp. During micro bait patterns, dead-slow-retrieving a small shad draws strikes from fish that ignore everything else. The combination of rolling action and subtle vibration is what triggers the bite.',
  'seabass-jointed-bait':
    'The S-shaped action born from a jointed bait\'s hinge point triggers the seabass predatory instinct. Its sinuous movement at dead-slow speed is the ultimate weapon — simply letting it drift in current can draw strikes from trophy-class fish. This is a lure that rewards the patient, methodical angler.',
  'seabass-crankbait':
    'Crankbaits control diving depth via the lip while generating stable wobble. The lip\'s grip on the water is easy to feel, making them efficient for searching shallow areas. Deflections off riprap and structure create erratic movements that trigger feeding responses.',
  'seabass-swimbait':
    'Swimbaits overcome pressured seabass with natural swimming action and realistic profiles. Choosing between one-piece and multi-jointed types to match conditions is key. They swim convincingly even at slow speeds and can work effectively from bottom to surface.',
  'black-bass-worm':
    'Soft plastics are both fundamental and endlessly versatile in bass fishing. Texas rigs, drop shots, and Neko rigs handle diverse presentations, and the slower you work them along bottom contours, the more likely you are to get bites on pressured waters. Size, color, and material selection directly determine your catch rate.',
  'black-bass-crankbait':
    'Crankbaits are ideal for efficiently searching large areas. Lip shape determines diving depth, so tracing tightly along weed tops and rock ledges is essential. The deflection-triggered erratic flash when contacting cover is the primary bite trigger for largemouth bass.',
  'black-bass-minnow':
    'Minnows truly shine for sight-fishing and spawn-period bass tactics. Flash and roll action provoke nest-guarding fish, and they coax bites from pressure-wise bass with natural presentations. Working shallow cover edges with a jerk-and-pause cadence is the textbook approach.',
  'black-bass-spinnerbait':
    'Spinnerbaits are all-purpose weapons combining excellent snag resistance for punching cover with blade flash appeal. They are particularly effective in stained water and low-light mornings. Slow-rolling near the bottom draws bigger bass and serves as a premier search bait across wide areas.',
  'black-bass-vibration':
    'Vibration plugs deliver outstanding search capability for bass in all seasons. Fast retrieves probe the mid-water column while bottom contact triggers reaction strikes. They see the most action during periods when depth is hard to read, such as winter deep patterns and post-turnover fall fishing.',
  'black-bass-rubber-jig':
    'Rubber jigs specialize in reaching big bass buried deep in cover. Skirt movement suggests bluegill or crawfish, while a slow fall lets the fish study and commit to the bait. Trailer selection dramatically changes the action profile, making fine-tuning directly impact your results.',
  'black-bass-bigbait':
    'Big baits are tools designed to selectively target trophy bass. Oversized profiles and heavy water displacement awaken the predatory instinct of the largest fish. They have a proven track record during pre-spawn spring and the fall feeding binge, demanding a strategic approach to target monsters on expansive fisheries.',
  'black-bass-shad':
    'Shad-profile lures excel at matching forage like smelt and minnows that bass feed on. The balance of tight wobble and roll translates directly into a feeding trigger, coaxing bites even when water temperatures drop and activity slows. Their ability to work from deep to shallow makes them extremely versatile.',
  'black-bass-popper':
    'A popper explosion on the surface is one of the most exciting moments in bass fishing. The sound and ripple pattern from the concave face triggers the bass attack instinct, bringing fish all the way to the surface. On shallow flats and around vegetation at dawn and dusk, a well-paced cadence with deliberate pauses is the key to success.',
  'black-bass-swimbait':
    'Swimbaits probe shallow to deep water uniformly as finesse-oriented lures. Soft, natural materials receive current and generate tail roll, coaxing bites from pressured bass without triggering suspicion. Range control comes from matching weight selection to retrieve speed.',
  'black-bass-chatterbait':
    'Chatterbaits combine high-frequency blade vibration with trailer action for a compound presentation. Their ability to cut through weeds and cover makes them user-friendly in dense structure. They are especially potent around the spawn, showing high selectivity for big bass.',
  'black-bass-pencilbait':
    'The walking-the-dog action of a pencil bait flips the feeding switch on bass. Working it slowly side-to-side and creating pauses for the fish to strike is fundamental. It is especially effective during dawn surface feeds and evening hours when bait moves to the surface.',
  'black-bass-buzzbait':
    'The continuous splashing sound and spray from a buzzbait\'s propeller draw bass to the surface. High-speed surface retrieves are the standard, and tracing along seawalls and reed lines dramatically increases blowups. On summer mornings and overcast days, the bite can last all day, delivering the pure essence of topwater bass fishing.',
  'black-bass-crawler-bait':
    'Crawler baits attract bass with the unique wave action and sound generated by their arms displacing water. They maintain action even at ultra-slow retrieves, making them effective during low-activity periods and high-pressure warm-water conditions. Early morning calm-water sessions see the most action.',
  'black-bass-frog':
    'Frogs enable a one-of-a-kind approach — skating across weed mats and lily pads. Pulling heavyweight bass through dense cover to the surface demands heavy line. The length of pause and timing after the cast are critical factors in triggering bites.',
  'black-bass-jointed-bait':
    'The S-shaped slalom action of a jointed bait faithfully replicates a living creature\'s swim. Its seductive movement at dead-slow speed visually stimulates big spawning-season bass with remarkable effectiveness. Adding jerks creates erratic movement, making it a multifaceted lure that also triggers reaction strikes.',
  'black-bass-metal-vib':
    'Metal vibes specialize in quickly probing deep-water bottoms. Vertical lift-and-fall presentations create a feeding window on the drop where bass commit. During winter low-water-temperature deep patterns, they rank among the most effective vibration-category techniques.',
  'black-bass-i-shape':
    'I-shaped lures are a secret weapon against pressured bass, running in an ultra-simple near-straight trajectory. Dead-slow-retrieving a slender shad or pintail worm just below the surface, drifting languidly, triggers the bass predatory instinct. They show their true value on clear, high-pressure fisheries.',
  'black-bass-spintail':
    'Spintail lures combine a worm body with blade flash, appealing to both sight and vibration. Slow-rolling through the mid-water column is the fundamental approach, where the reflected light from the blade flips the feeding switch. Even on pressured waters, their unique action coaxes bites.',
  'black-bass-propbait':
    'The sound and ripple pattern from a propbait\'s prop blades attract bass from a wide area. Combining pauses with short twitches to intentionally create strike windows is the key to success. Deploying them during dawn and dusk when bass are surface-oriented maximizes trophy-class opportunities.',
  'black-bass-sinking-pencil':
    'Sinking pencils coax strikes from bass with their shimmer and horizontal posture during the fall. Feeding slack line and letting them drop creates an irregular fluttering motion that triggers reaction bites. Pausing during a slow mid-water retrieve lets trailing bass commit on the subsequent fall.',
  'black-bass-blade-bait':
    'Blade baits leverage the intense vibration and flash from thin metal bodies. Vertical lift-and-fall tactics are especially effective on deep bass, with proven ability to coax bites even during peak winter cold. Their compact silhouette relative to weight is an additional advantage.',
  'black-bass-topwater':
    'Topwater fishing, where you witness the strike firsthand, delivers the ultimate adrenaline rush. Focusing early morning casts during calm surface conditions draws big shallow-suspended bass into aggressive surface strikes. Timing and spot selection matter more than lure type.',
  'black-bass-jighead':
    'Jighead rigs paired with shad tails or curly tails for swimming presentations are the standard approach. Light heads for shallow work and heavy heads with fall pauses for deep bottom tactics offer tremendous range flexibility. Reading terrain and dialing in the optimal depth zone is key.',
  'trout-spoon':
    'The spoon is the origin of trout fishing and remains the most versatile lure. Weight and size adapt to current speed and depth, producing diverse actions from slow rolls to fast retrieves. Flash reflects particularly well under overcast skies and at dawn, when strikes tend to concentrate.',
  'trout-minnow':
    'Trout minnows work across a wide range of scenarios, from mountain streams to managed fisheries. Heavy sinking types hold their range in strong current and flash to effectively target char and yamame trout. Drifting into current seams and delivering the lure behind boulders is the technique that determines success.',
  'trout-crankbait':
    'Trout crankbaits reach their full potential during dead-slow tactics at managed fisheries. The lip stabilizes diving depth while generating subtle wobble that triggers responses from inactive rainbow trout. Simply dropping the retrieve speed can dramatically improve your catch rate.',
  'trout-spinner':
    'The rotating blade flash of a spinner is the fastest route to triggering a trout reflex strike. Adjusting retrieve speed to maintain consistent blade rotation in current is fundamental — the instant the blade stalls, the bites stop. Upstream casting and retrieving back is the textbook approach.',
  'trout-vibration':
    'Trout vibration lures provide the mobility to search a wide range of depths for pressured fish at managed fisheries. Focus on micro-class sizes during low-light conditions with a slow retrieve for consistent results. Bites frequently come during the fall, making line tension management essential.',
  'trout-sinking-pencil':
    'Sinking pencils counter trout wariness with their natural movement. The drifting, fluttering fall imitates a wounded baitfish, triggering feeding responses. In mountain streams, casting into whitewater riffles and drifting can produce fish from unexpected lies.',
  'trout-spinnerbait':
    'Trout-sized spinnerbaits feature single blades and suit searching in lakes and ponds with lower fishing pressure. Blade flash and water displacement attract cherry salmon and landlocked salmon from a wide area. Slow-rolling near the bottom in deeper zones tends to draw bigger fish.',
  'bluerunner-metal-jig':
    'The metal jig\'s casting range and fast sink rate are the ultimate weapons for pelagic species. Alternating jerks and falls across multiple depths provokes chase strikes from yellowtail and amberjack. Select weight at roughly three times the water depth, sink to the bottom, then work back up with one-pitch jerk retrieves.',
  'bluerunner-minnow':
    'Minnows for pelagics deliver a perfect match-the-hatch presentation for sardines and anchovies. Working them with a jerk-and-pause cadence after a long cast produces flash and sudden stops that trigger strikes. During surface blitzes, start retrieving immediately after splashdown to connect with Spanish mackerel.',
  'bluerunner-popper':
    'Nothing matches the excitement of casting a popper into a pelagic surface blitz. The splash and sound from the cupping face further excite fish already chasing bait, drawing explosive surface strikes. Combining fast dog-walking jerks with quick pauses reduces missed hookups.',
  'bluerunner-sinking-pencil':
    'The sinking pencil is a staple of pelagic fishing. Fall-bite patterns dominate, so count down to target the layer just below the surface commotion and entice with slow wobble. They are especially effective around current seams and tidal transitions, where pausing after a jerk concentrates the bites.',
  'bluerunner-diving-pencil':
    'Diving pencils use rod work to grab the water, producing distinctive splash-and-dive action that draws pelagics in. The subsurface swim provides high visual excitement and readily flips the feeding switch. Rhythmic rod work is essential, with dawn and dusk windows producing the most consistent results.',
  'bluerunner-pencilbait':
    'Pencil baits entice pelagics with dog-walking and splash presentations on the surface. They are ideal for surface-blitz situations where bait is being pushed up, and varying between stop-and-go cadences serves as the feeding trigger. Check the swim action by adjusting hook size and rigging before starting.',
  'bluerunner-vibration':
    'Vibration lures shine when pelagic activity slows or when targeting deeper zones. Lift-and-fall and steady retrieves search a wide area, and their strong water displacement maintains presence even in dim pre-dawn conditions. Varying the countdown to locate the cruising depth is the fundamental approach.',
  'bluerunner-spintail':
    'The blade flash and vibration from a spintail appeals directly to the pelagic predatory instinct. A simple steady retrieve generates sufficient action, and the blade continues spinning even during the fall. The stronger the current at a given spot, the faster the blade spins, amplifying its appeal.',
  'bluerunner-metal-vib':
    'Metal vibes sink fast, reaching the bottom reliably even in deep water or strong winds. Repeated lift-and-fall cycles thoroughly cover the near-bottom zone, excelling when pelagics are pinning bait against sandy or rocky structure. Maintaining stable operation against the current is the key to boosting your catch rate.',
  'bluerunner-worm':
    'Soft plastics for pelagics may seem unconventional, but they have a strong track record for surface blitzes and topwater tactics. During whitebait patterns, fast-retrieved pintails and paddle tails produce outstanding results. Better hookup rates and fewer lost fish compared to jigs make them a trump card on pressured waters.',
  'bluerunner-bigbait':
    'Big baits target trophy-class pelagics exclusively. Oversized silhouettes and strong wobble reach fish at distance, pulling in specimens that ignore other lures. For targeting big yellowtail and amberjack from surf or rocky shores, these are the go-to for making an impact.',
  'bluerunner-swimbait':
    'Swimbaits coax bites from pressured pelagics with realistic baitfish silhouettes and natural tail action. They hold high rotation value during periods when jigs and vibes fail to produce, maintaining presence even at slow retrieves. Deploying them when the current slackens is particularly effective.',
  'bluerunner-jighead':
    'Jighead rigs allow precise depth control, making them powerful when pelagics concentrate at a specific layer. Adjusting weight and counting down to dial in the range while fine-tuning action via worm selection is fundamental. The lighter tackle setup amplifies the fight, delivering a more direct connection to big fish.',
  'hirame-minnow':
    'Flounder minnow tactics are all about tracing the near-bottom zone for as long as possible. Begin the retrieve just before the lure touches down and maintain a 30-50cm depth off the bottom while avoiding snags. Switching between deep-diving long-lip models and floating types stabilizes your range even in rough surf conditions.',
  'hirame-metal-jig':
    'The metal jig\'s casting distance and sink rate are key weapons for Japanese flounder. Launch from surf or jetties to reach offshore breaks, and work the bottom with lift-and-fall cadences. Bites frequently come during the fall, so maintaining consistent tension and reading line movement for subtle takes is critical to success.',
  'hirame-worm':
    'Soft plastics are indispensable for slow presentations targeting flounder. A shad tail crawled slowly near the bottom swims enticingly just above the sand, creating a powerful visual trigger. The colder the water and the tougher the conditions, the more natural worm action comes into its own, picking up fish that ignore hardbaits.',
  'hirame-sinking-pencil':
    'For surf flounder, drifting a sinking pencil naturally in the current is the most effective approach. Manage the sink via countdown after splashdown and begin the retrieve just above the bottom. Natural wobble provides a subtle appeal, while pausing after a jerk triggers bites.',
  'hirame-vibration':
    'Vibration lures have the power to alert distant flounder to your presence. Cast long, sink quickly to bottom, then maintain range through lift-and-fall sequences. Their stable underwater action even in murky or windy conditions provides reliable catch rates in rough sea states.',
  'hirame-spintail':
    'The blade flash of a spintail draws flounder from distance. Slow-retrieving near the bottom keeps the blade spinning and reflecting light even in subtle current. Particularly effective during low-light early mornings and evenings, when flounder prowl the bottom searching for prey.',
  'hirame-swimbait':
    'The realistic profile and fluid tail action of a swimbait is devastatingly effective on pressured flounder. It is a valuable rotation option for midday sessions when pressure builds. Adjusting weight via jighead pairing and keeping the lure swimming just above the bottom is the standard style.',
  'hirame-bigbait':
    'Big baits for flounder are a strategy for selectively targeting trophy-class specimens. Fish that respond to large silhouettes generally run bigger, allowing you to target fish over 60cm. Slow presentations in deeper surf zones and harbor outflows can produce spectacular chase-and-strike bites.',
  'rockfish-worm':
    'Targeting rockfish with soft plastics is all about reading structure and current, presenting as slowly and naturally as possible. Texas rigs and free rigs with grubs or creature baits let you probe cracks and tight spots along rocks. When you detect a subtle line twitch or weight increase during the fall, set the hook immediately.',
  'rockfish-jighead':
    'Jighead rigs are ideal for light probing around rocky structure. Slowly tracing along rock faces on the drop draws fish out of hiding. Select the lightest weight that still maintains bottom contact for the given current and depth, carefully tracking the sensation of each bottom touch.',
  'rockfish-metal-jig':
    'Metal jigs are the choice when targeting medium-to-large rockfish or searching deeper water broadly. Short-pitch jerks and lift-and-fall presentations trigger reaction strikes. Methodically working mid-water to near-bottom with tight action overcomes the ambush-style behavior of rockfish.',
  'rockfish-minnow':
    'Targeting rockfish with minnows finds its ideal setting along shallow rocky shelves and reef platforms. Cast tight to cover and twitch to draw immediate strikes from fish that are actively chasing bait. Choose short-lipped floating minnows and present with lateral movement slightly above the bottom rather than hugging it.',
  'rockfish-sinking-pencil':
    'A sinking pencil becomes an interesting option when rockfish are active near the surface. Slowly sinking a slow-sinking type while letting it drift draws strikes from suspended fish reacting to the fall. Casting to shallow reef edges and rock faces during hot bites can produce surprising trophy catches.',
  'mebaru-worm':
    'Rockfish worming comes down to range management and fall speed control. Thread a 1-2 inch pintail or grub onto a jighead and let the current carry it down slowly. Bites often come the instant tension is released — reading subtle line changes and detecting the slightest weight increase is the key to maximizing your count.',
  'mebaru-jighead':
    'Jighead rigs for rockfish rely on lightness and finesse. Drifting worms slowly on 0.5-1.5g jigheads at the edge of light-shadow transitions and streetlight perimeters draws bites. Pairing with a float rig extends reach to offshore spots, efficiently covering areas that hold bigger fish.',
  'mebaru-minnow':
    'Minnow tactics for rockfish center on tracing just below the surface. Slow-retrieving a floating minnow draws following fish that strike the moment it pauses. Especially effective around streetlights at night — start with silhouette-type colors that stand out in the light for the highest-percentage approach.',
  'mebaru-sinking-pencil':
    'When targeting rockfish with sinking pencils, the key is to create a subsurface drifting presentation. Slow steady retrieves or drifting naturally draw bites from pressured fish. When rockfish are rising under streetlights, this low-resistance lure shows outstanding effectiveness.',
  'mebaru-vibration':
    'Micro vibration lures serve as a trump card when jigheads are not producing. They shine during daytime bottom-probing sessions or when rockfish have retreated to deeper water in cold temperatures. Short falls after a lift trigger reaction strikes, picking up fish that respond readily to moving targets.',
  'aji-worm':
    'In light-game horse mackerel fishing, soft plastic texture and action finesse directly impact your catch rate. Pair a slim 1-2 inch pintail with a jighead and let the current carry it on a free fall. In low-light night sessions, minimize movement and focus on detecting bites through subtle line tension changes — this sensitive approach is the essence of productive ajing.',
  'aji-jighead':
    'In horse mackerel fishing, jighead weight selection dictates everything. Read current strength and depth to find the weight that sinks just slowly enough under tension. Maintain controlled but not excessive line tension to detect fall bites, managing various depth ranges via countdown.',
  'aji-metal-jig':
    'Metal jigs for horse mackerel efficiently locate migrating schools. Vary the retrieve depth during a steady mid-water retrieve and concentrate on the layer that produces responses. A spoon-like approach with small metal jigs also works well, and jigs with good casting distance excel at reaching offshore current seams during daytime sessions.',
  'aori-ika-egi':
    'In squid jigging, the cadence of the rod snap and subsequent fall time management determines your success. Autumn squid aggressively chase the jig, so a two-to-three snap sequence followed by a controlled fall is the go-to technique. Spring trophy specimens are more cautious, requiring extended falls. Drifting with the current efficiently covers a wide area, making it easier to locate big squid.',
  'madai-tai-rubber':
    'With tai-rubber, selecting the right skirt color and head weight is where the battle begins. Vary the retrieve speed while matching the boat drift to re-establish bottom contact, searching for the layer where red sea bream feed upward. When you feel the telltale tap-tap-tap of a preliminary bite, maintain speed without changing, and wait until the rod loads fully before setting the hook.',
  'madai-metal-jig':
    'When targeting red sea bream with metal jigs, the basic approach is repeated slide-falls worked slowly upward from the bottom. Bites concentrate during the fall, so reacting quickly to line movement and slack is what raises your hookup rate. Silver and gold flash colors are especially effective during bright-light conditions.',
  'kurodai-worm':
    'Drifting worms downstream and rolling them along the bottom is devastatingly effective for black sea bream. Crawfish-imitating claw-type worms crawled naturally along the bottom stay in the feeding zone longer. Work tight to structure, and keep in mind that the majority of bites come during the fall.',
  'kurodai-popper':
    'For topwater black sea bream, harbors and shallow river sections provide the best stage. The popping sound and ripple pattern stimulate the predatory instinct, producing explosive surface strikes. Fish tend to strike immediately after the lure stops, so creating a clear move-and-pause rhythm directly translates to more catches.',
  'tachiuo-metal-jig':
    'Vertical jigging from boats is the primary approach for cutlassfish with metal jigs. Slim-profile jigs maintain excellent fall posture and produce deep hooksets. Pinpoint the school by systematically varying depth ranges, then draw reaction strikes with short jerks followed by controlled falls — that is the essence of this game.',
  'tachiuo-worm':
    'Soft plastics deliver strong results for cutlassfish from shore. Thread elongated shad tails or ring worms on light jigheads and slow-retrieve through the mid-water column to intercept the cutlassfish lateral feeding movement. Wire-hook-equipped soft plastics handle their razor teeth while dramatically improving hookup rates.',
  'hiramasa-metal-jig':
    'Jigging for amberjack is a battle of stamina and concentration. Repeated long-stroke jerks probe a wide range from bottom to mid-water, with constant readiness to detect the critical fall bite. Assist hook sizing and rigging are paramount — ensuring enough give to track the fish\'s explosive initial run is the fundamental anti-break-off strategy.',
  'hiramasa-diving-pencil':
    'Diving pencil games for amberjack offer the ultimate surface excitement from rocky shores or offshore. The large cup grabs water to generate splash, and consecutive dives draw fish in. Matching rod angle to retrieve rhythm to produce a regular action pattern is the secret to bringing amberjack all the way to the surface.',
  'hiramasa-popper':
    'Speed is critical when casting a popper at amberjack boils. The big popping sound and spray draw in surrounding fish, and witnessing the chase-to-strike sequence on the surface delivers an experience unlike any other in fishing. Work the rod high to make the popper skip off the surface — that is the fundamental action.',
  'kampachi-metal-jig':
    'Greater amberjack tend to hold tight to bottom structure, making bottom jigging with metal jigs the core strategy. Fearlessly sink to the bottom and work tight to structure with fast-tempo short-pitch jerks. Keep feeding falls short, targeting reaction strikes to draw out the explosive bites that greater amberjack are known for.',
  'kampachi-diving-pencil':
    'Diving pencil topwater games for greater amberjack reach their peak around offshore pinnacles and seamounts. The sight of a fish rocketing up from below to hit a lure splashing through the surface is truly jaw-dropping. Greater amberjack make stronger straight-line runs than yellowtail amberjack, demanding robust tackle setups as a prerequisite.',
  'tuna-metal-jig':
    'Tuna jigging is the highlight of offshore fishing. High-pitch jerks work the jig from mid-water to bottom, and timing your presentation to coincide with a passing school is everything. Drift-jigging on the current also produces results — following the captain\'s guidance on target depth is the fundamental basis of success.',
  'tuna-diving-pencil':
    'Diving pencils are most effective for tuna when targeting surface-feeding schools. Cast into the center of a bird pile, grab the water, and work a fast retrieve to draw tuna through the surface for explosive strikes. Always verify that hook strength and rod butt power can withstand a tuna\'s first devastating run before engaging.',
  'tuna-popper':
    'Poppers for tuna aim to simulate panicked baitfish using a large cup. Leverage casting distance to draw fish from a wide area, and rapid consecutive pops portray fleeing bait, bringing tuna crashing through the surface. Proper drag settings and powerful rod work to control the initial run are absolute requirements for getting fish to the boat.',
  'yellowtail-metal-jig':
    'Shore jigging for yellowtail with metal jigs is the foundation of pelagic fishing. Leverage casting range to target surface blitzes and current seams, starting the one-pitch jerk retrieve immediately after splashdown to probe the mid-water column. Reading migration timing, choosing your position, and covering water broadly rather than hammering one spot is the shortcut to building a solid catch tally.',
  'gt-popper':
    'Targeting giant trevally with poppers is the pinnacle of fishing — a test of both stamina and nerve. The thunderous sound and water columns generated by an oversized cup draw GTs from dozens of meters away, and the impact of a surface strike is unparalleled. Continuous popping with aggressive rod sweeps builds excitement, with the classic pattern being a strike the moment the lure pauses.',
  'gt-diving-pencil':
    'Diving pencils for GT carry more depth than poppers, enabling longer subsurface chases. The fundamental technique combines rod work to submerge the lure with quick retrieves — once a GT locks on from behind, maintaining pace without slowing is the key to converting the follow into a strike. Rocky shores and outer-reef edges provide the ultimate arena.',
  'gt-metal-jig':
    'Jigging for GT plays out in deep open water and around structure. Driving heavy jigs with long-stroke jerks is a pure endurance contest, and the tackle balance to absorb the crushing initial strike determines everything. Detecting fall bites and setting the hook instantly, then applying enough rod power to prevent a charge into the reef — that is the level of strength demanded.',
  // ── Batch 2 ──
  'bass-bigbait':
    'This is the category for hunting big bass that eat big prey. Big baits possess the silhouette realism and water displacement to coax bites even on pressured fisheries. When a 200g-plus lure tears across the lake surface, every single cast carries meaning.',
  'bass-blade-bait':
    'A vibration-type metal plate shudders at high speed, searching a wide area with tight wobble. Devastatingly effective for forcing strikes in winter deep zones or stained water. Lift-and-fall reaction tactics are another classic application.',
  'bass-buzzbait':
    'The surface strike is something you will never forget. The continuous splashing sound and spray from the blade call bass in. Running the mat cover and reed edges at speed delivers the full thrill of topwater bass fishing.',
  'bass-chatterbait':
    'The erratic blade vibration and wave action maintain presence even in stained water. The combination of skirt flutter and jig-head movement creates a compound appeal that triggers bass. From weed edges to open water, this is the power-style trump card for all seasons.',
  'bass-crankbait':
    'The lip grabs water and drives the lure at its designed range with a tight wobble. Having one in your bag means you can instantly search a wide area. Bottom contact generates irregular action, and that is exactly where bass concentrate their instinctive strikes.',
  'bass-crawler-bait':
    'Wings or arms move slowly, spreading ripples and bubbles across the surface in the ultimate slow game. Working the surface quietly in night or overcast low-light conditions draws trophy bass up through the water column for explosive surface strikes.',
  'bass-frog':
    'Walk it across the mat and drop it into a pocket to trigger the bite. Walking the dog along lily pads while portraying a realistic frog draws even big bass from deep in cover for an explosive surface blowup.',
  'bass-i-shape':
    'Barely moving — almost just being there. The straight-line retrieve deceives finicky spawning-phase bass and slow seasonal fish through sheer non-action. The contrast between its unassuming appearance and actual catch rate makes it a genuine secret weapon.',
  'bass-jointed-bait':
    'The sensuous S-shaped action born from the joint. A fish-like swimming motion draws trophy bass in on pure instinct. The slower you retrieve, the more seductive the swim becomes — this is a front-line lure that continues to reign for big-fish pursuits.',
  'bass-metal-vib':
    'The mobility of a blade-style vibration lure covers everything from winter deep zones to shallow breaks. High density delivers long casting distance, reaching pressured far banks and breaklines in a single cast.',
  'bass-minnow':
    'Tight wobble and shimmy fall draw out bass that refuse every other lure. Twitched dart action perfectly replicates a fleeing baitfish. A proven pattern that is particularly deadly on post-spawn bass.',
  'bass-pencilbait':
    'Walking the dog with rod work is the foundation. Subtler splash than a popper draws bass from a wide area, and maintaining a steady rhythm is the shortcut to consistent catches.',
  'bass-popper':
    'The cup catches water, producing a distinct pop-pop sound that calls bass from distance. The splash and sound combination simultaneously triggers visual and auditory senses. Bites concentrate during the pause drift, demanding the patience to wait without rushing.',
  'bass-propbait':
    'The tail propeller spins, creating fine bubbles and sound waves on the surface. A more delicate presentation than a popper that coaxes bites from pressured bass without raising suspicion. Extended-pause twitch-and-stop cadences are most effective.',
  'bass-rubber-jig':
    'The rubber skirt breathes in the water, drifting slowly along structure. From football heads to arky heads, it covers everything from finesse to power fishing as the undisputed king of bottom tactics.',
  'bass-shad':
    'The tail kicks with the most fish-like body form available. A straight retrieve produces a seductive swim, and pairing with a swim jig or weighted hook delivers flawless mid-range coverage. A quietly productive soft plastic masterpiece.',
  'bass-sinking-pencil':
    'Maintaining a horizontal posture while sinking, it draws bites throughout the fall. Lift-and-fall vertical presentations leverage the sinking style. This lure bridges the gap between hardbait casting distance and soft plastic finesse.',
  'bass-spinnerbait':
    'Blades broadcast light and vibration simultaneously, announcing presence to bass in stained water or darkness. Blade selection changes the approach, and the ability to deflect cover while efficiently searching a wide area is what makes them so popular.',
  'bass-spintail':
    'A shad-bodied lure with a tail spinner produces diverse action through jerks and falls. The spinner\'s reflected flash appeals to bass across a wide area, filling the sweet spot between soft plastics and hardbaits.',
  'bass-spoon':
    'A simple metal plate swims with a flutter, mimicking the flash of baitfish. There are absolutely situations where only a spoon will produce. Vertical lift-and-fall, horizontal swimming — one plate enables a diversity of presentations that represents the angler\'s roots.',
  'bass-swimbait':
    'Realistic fish silhouettes and precise tail action deceive wary trophy bass. Matching the gill or shad forage size creates a perfect match-the-hatch presentation. A dedicated finesse lure for medium-speed retrieves.',
  'bass-topwater':
    'The moment a bass explodes through the surface is what this entire pursuit is about. Poppers, pencils, crawlers — surface games are every bass angler\'s eternal aspiration. Focus on dawn and dusk, and dead-calm conditions only amplify the explosive potential.',
  'bass-vibration':
    'Cast and retrieve — it vibrates automatically, quickly searching wide ranges and areas. Rattle models excel at reaction strikes in stained water, while silent versions show their true power in clear conditions. A trusted search lure across all seasons.',
  'bass-worm':
    'If you have worms, you can fish. Weightless, Texas, drop shot — the rigging options are infinite, adapting to any condition. Tail action stimulates both appetite and curiosity simultaneously, making this a lure where technique directly translates to results.',
  'seabass-chatterbait':
    'Blade vibration carries through waves to reach seabass. Action remains stable even in river current, proving strong against bottom-feeding pressured seabass. Heavier models also serve effectively as daytime search baits.',
  'seabass-crawler-bait':
    'The crawling surface action drives seabass wild on nighttime rivers. When the sandworm hatch pattern connects, you can witness seabass slowly sipping the lure from behind. Commit to dead-slow retrieves with patience, and the catches will follow.',
  'seabass-diving-pencil':
    'A fast retrieve after the cast sends it diving, and adding jerks creates darting action that breaks from the zone. Essential for targeting seabass surface blowups. The casting distance and diving capability efficiently cover vast surf and river mouth areas.',
  'seabass-i-shape':
    'Nearly motionless, yet they bite. The I-shape retrieve introduced finesse concepts to the seabass game. Devastatingly effective on pressured urban rivers and slow winter seas. Bites from below or the side frequently occur the moment the rod stops.',
  'seabass-other':
    'The seabass game encompasses diverse tactics. This category covers vibration lures, jigs, jighead rigs, and more for situation-specific deployment. Selecting to match the day\'s seabass behavior patterns, rather than sticking to conventions, is what separates catch rates.',
  'seabass-propbait':
    'The subtle sound and bubbles from the propeller draw in feeding-mode seabass. A middle-ground topwater that is less conspicuous than a popper yet more action-driven than a pencil. Produces consistent surface bites during night sessions.',
  'seabass-spinner':
    'An underwater rotating blade scatters light, maintaining presence even in current. It readily serves as a trigger when seabass are present but refusing to commit under pressure. Even a straight retrieve produces bites in many situations.',
  'seabass-spinnerbait':
    'Spinnerbait wave action and flash appeal aggressively to seabass in rivers and surf. Capable of tight approaches around bridge pilings and rocky reefs, with particularly high reliability during stained-water daytime sessions.',
  'seabass-spoon':
    'Metal flash and fluttering fall trigger seabass reaction strikes. The standard approach is searching broad surf and river mouth areas with a metal spoon, reaching distant surface blitzes with long casts. Consistent performance even in strong wind conditions.',
  'seabass-sutte':
    'Squid-jig-style bottom presentations specialize in seabass around river obstructions and tetrapod structures. The irregular fall posture, distinct from a jighead, creates the feeding trigger — effective on bottom-oriented inactive seabass.',
  'seabass-tai-rubber':
    'This method originated from adapting tai-rubber for seabass. The slow fall and skirt flutter stimulate the predatory instinct, producing bites on a simple slow retrieve from bottom to mid-water. A strong pattern during low-activity winter periods.',
  'seabass-topwater':
    'Casting a topwater into seabass blowups at summer dawn is an incomparable thrill. Seabass chasing mullet and juvenile fish on shallow tidal flats will strike at the surface. Explosive bites and water columns create the supreme moment in seabass fishing.',
  'bluerunner-blade-bait':
    'High-speed steady retrieves with blade vibration flip the switch on pelagics. Freely range from bottom to surface while efficiently searching yellowtail and amberjack schools. One-pitch jerk reaction tactics leveraging casting distance and sink rate deliver results.',
  'bluerunner-crankbait':
    'During peak feeding hours, a crankbait\'s trace depth and wobble deliver explosive effectiveness against pelagics. High-season surface cranking produces savage topwater strikes. Vary retrieve speed to dial in the sweet spot.',
  'bluerunner-crawler-bait':
    'When pelagics pin bait against the surface, the water-noise from a crawler bait strikes directly at the predatory instinct. Watching yellowtail and amberjack break the surface is an excitement only experienced firsthand.',
  'bluerunner-i-shape':
    'A finesse approach deployed when pelagics refuse to commit. Catch reports — particularly from amberjack games — have overturned doubts about whether I-shape retrieves work on pelagics. Functions as a trump card during lock-jaw situations.',
  'bluerunner-jointed-bait':
    'The S-curve from a segmented body awakens the hunting instinct of trophy pelagics. Enables a selective approach targeting trophy amberjack and yellowtail. The wake and silhouette create a convincingly realistic baitfish presentation.',
  'bluerunner-other':
    'Pelagic fishing encompasses a variety of approaches. Unconventional lures like tungsten jigs and specialty plugs frequently break through when standard categories fail. The more options you carry for varying fields and seasons, the greater your advantage.',
  'bluerunner-propbait':
    'Cast a propbait splashing into a surface blitz and pelagics commit without hesitation. In amberjack topwater games, the prop rotation sound frequently serves as the bite trigger, delivering overwhelming explosive potential during bait-pinning scenarios.',
  'bluerunner-shad':
    'The realistic action of a shad tail precisely targets pelagics that are selectively feeding on bait. Size-matching to anchovy and silverside profiles is critical, and pairing with a swim jig for a match-the-hatch presentation produces strong results.',
  'bluerunner-spinner':
    'A spinner\'s blade-generated light and vibration possess wide-area search capability across open water. Fast steady retrieves through yellowtail schooling zones can sometimes produce chain reaction strikes.',
  'bluerunner-spoon':
    'Combining long casting range with intense flash, spoons are the star of pelagic surf games. The distance advantage reaches offshore blitzes, and posture stability holds even at high-speed retrieves. A versatile all-rounder covering yellowtail, amberjack, and greater amberjack.',
  'bluerunner-sutte':
    'Squid-style jigs dropped deep and worked upward address the vertical movement patterns of pelagics. Effective when big yellowtail stack near the bottom. Concentration to detect fall bites and fast hooksets determine your success rate.',
  'bluerunner-tai-rubber':
    'Tai-rubber producing pelagic bites happens more often than you might expect. The skirt flutter is devastatingly effective on bottom-pinned yellowtail and greater amberjack. Slow-retrieve-to-fall combinations coax bites even in high-pressure waters.',
  'bluerunner-tenya':
    'Pelagics respond to tenya rigs primarily when bait dives deep. Shrimp and small-fish profiles combined with the unique fall action draw strikes from yellowtail and amberjack. Varying the jerking cadence and fall duration is the key.',
  'bluerunner-topwater':
    'Surface explosion. Watching amberjack blast a diving pencil is the pinnacle of shore fishing. Long casts from rocky shores or surf followed by high-speed diving action provoke amberjack attacks. The physical fight that follows is an experience that changes an angler.',
  'black-bass-egi':
    'Targeting largemouth bass with squid jigs may seem unorthodox, but it makes perfect sense for pre-spawn fish selectively feeding on crawfish. Bottom darts and falls coax bites from wary pre-spawn trophy bass, gaining attention as a viable tactic.',
  'black-bass-metal-jig':
    'Using metal jigs for bass specializes in high-speed reaction presentations for winter deep water or stained conditions. The irregular fall action flips the feeding switch, and the ability to probe a wide range vertically is the greatest strength. Functions as a game-changing wild card.',
  'black-bass-other':
    'Largemouth bass fishing thrives on creativity that breaks convention. This category encompasses approaches from finesse rigs to big baits that push beyond established norms. The ability to flexibly adapt to changing conditions and seasons is what drives angler development.',
  'black-bass-spinner':
    'Spinner blade flash and strong wave action simultaneously stimulate the bass fight response and reaction instinct. Slow-rolling along weed edges and cover delivers consistent results in stained water and low-light conditions.',
  'black-bass-spoon':
    'Spoon flash and natural flutter draw bass into feeding mode. Covering a wide range from surface to bottom with lift-and-fall and swimming retrieves, the simple plate format holds infinite versatility for bass applications.',
  'black-bass-tai-rubber':
    'Adapting tai-rubber for largemouth bass has gained attention as an emerging approach. The rubber pulsation and head fall speed stimulate the predatory instinct, proving effective on deep-suspended bass and during tough-bite conditions.',
  // ── Batch 2: trout, flounder, black sea bream, etc. ──
  'trout-crawler-bait':
    'Crawler bait surface action and wave displacement trigger the trout predatory instinct. From managed fisheries to mountain streams, slow-retrieving the surface produces results — deploy during rise-heavy dawn and dusk windows for explosive surface strikes.',
  'trout-jighead':
    'A jighead rig that can precisely segment depth ranges is a versatile system for searching bottom to surface. Adjusting wave action and silhouette through worm selection produces consistent results even at pressured managed fisheries.',
  'trout-jointed-bait':
    'The alluring S-curve trajectory from a jointed body draws out the trout chase instinct. Generating lifelike action even at dead-slow speeds makes it a trump card during cold-water and inactive periods. Also appeals strongly to trophy-class char in mountain streams.',
  'trout-metal-jig':
    'Leveraging casting range and fast sink rates to pick off trout on offshore breaks and deep zones. Maximizing flash through lift-and-fall presentations triggers aggressive strikes even in low-visibility stained water.',
  'trout-metal-vib':
    'The high-frequency vibration from a metal body directly targets the trout lateral line. Wide-ranging coverage from fast retrieves to ultra-slow presentations makes it a trump card for winter bottom tactics and fast-flowing main river channels.',
  'trout-other':
    'Unconventional lures outside standard categories expand the possibilities of trout fishing. A deep arsenal of situational approaches reaches its full potential in those critical moments that separate experienced anglers from beginners.',
  'trout-pencilbait':
    'Pencil bait walking-the-dog action maximally stimulates trout aggression. Using line slack for twitching to generate side-to-side head shakes draws yamame and trophy rainbow trout to break the surface with violent strikes.',
  'trout-popper':
    'The pop sound and splash instantly engage the trout feeding switch. The cup-generated sound simulates an insect fall, making it the ultimate weapon for drawing yamame and amago to the surface on summer mountain streams.',
  'trout-propbait':
    'The chattering sound and fine ripples from the propeller stimulate trout curiosity. The continuous water noise during slow retrieves is especially effective during active hatch periods, drawing even trophy rainbow trout into unhesitating surface strikes.',
  'trout-shad':
    'The natural swim generated by subtle tail vibration possesses extraordinary finesse capability against trout. Even under severe clear-water conditions, it draws bites without triggering suspicion — an all-rounder delivering consistent results regardless of fish size.',
  'trout-topwater':
    'Explosive strikes on a surface lure drifting just below the top are the ultimate thrill of trout fishing. Deploy during evening rise time to draw aggressive attacks from trophy char and rainbow trout for the most exciting session of all.',
  'trout-worm':
    'The natural wave action of soft material disarms the wariness of pressured trout. Weightless drifts and drop shots overcome shut-down fish, providing a reliable approach for breaking through difficult conditions at managed fisheries.',
  'hirame-crawler-bait':
    'The swimming wobble of a crawler triggers flounder reaction strikes. Carefully tracing the breakline in surf conditions draws flounder up from their sandy ambush positions for aggressive bites.',
  'hirame-other':
    'When jigs and minnows fall short, alternative approaches open new doors. A flexible eye for matching surf conditions and tidal changes creates opportunities to precisely target flounder holding spots.',
  'hirame-pencilbait':
    'A pencil swimming in an S-curve just below the surface draws flounder up in the surf. Beyond high-activity scenarios, a dead-slow presentation along the wave wash zone produces dramatic strike sequences.',
  'hirame-popper':
    'Popper splash and pop sounds stimulate the flounder predatory instinct. Working a dog-walk presentation in ultra-shallow surf areas and rip current zones draws flounder that have been chasing bait all the way to the surface.',
  'hirame-magochi-jighead':
    'A jighead-and-worm combination is the ultimate bottom-probing tactic for flatfish. Confirming bottom contact and working lift-and-fall along sandy bottoms efficiently targets both flounder and flathead simultaneously.',
  'hirame-magochi-metal-jig':
    'Target offshore breaks and deep zones for flounder and flathead with the advantage of long casts. Fast-sinking to establish bottom quickly, then slow lift-and-fall presentations extend the time spent in the strike zone.',
  'hirame-magochi-minnow':
    'A minnow\'s wobble tracing tight to the bottom triggers flatfish feeding responses. Slow-retrieving along surf breaklines and drop-offs creates a powerful appeal to both flounder and flathead lying in ambush.',
  'hirame-magochi-sinking-pencil':
    'A sinking pencil that counts down to establish the bottom range and works at dead-slow speed directly approaches flounder and flathead pinned to the surf bottom — a high-precision lure for this application.',
  'hirame-magochi-worm':
    'The subtle wave action of soft plastics stimulates the sensitive lateral line of flatfish. Working the bottom slowly with Texas rigs or jigheads while avoiding snags draws aggressive bites from both flathead and flounder.',
  'kurodai-metal-vib':
    'High-density metal vibe steady retrieves trigger reaction strikes from black sea bream. Fast-swinging along cobble beaches and rocky shoreline bottoms taps into the territorial aggression of chinu for an explosive approach.',
  'kurodai-minnow':
    'A minnow tightly tracing rocky shallows and eelgrass beds draws black sea bream out. From slow winter retrieves to fast summer presentations, it covers a wide range while boosting chinu hookup rates.',
  'kurodai-other':
    'An inventive lure collection that broadens the possibilities of black sea bream fishing, enabling situation-matched approaches across diverse fields including rivers, tidal flats, and rocky shores.',
  'kurodai-pencilbait':
    'Pencil bait walking the dog elevates the black sea bream topwater game to its peak. When you hear feeding sounds on the shallow flat, throw the pencil immediately. A surface-strike from chinu is an experience you will never forget.',
  'kurodai-sinking-pencil':
    'The subtle range-holding ability of a slow-sinker is the key to cracking pressured black sea bream. River current drifts and slow presentations along structure open the mouth of visible chinu.',
  'kurodai-spoon':
    'Spoon flash and natural swimming action stimulate the black sea bream instinct. Slow retrieves while drifting in the current are highly effective against chinu in harbor areas and surf zones.',
  'kurodai-vibration':
    'Vibration lure wave action and flash simultaneously stimulate black sea bream curiosity and reaction instinct. Bottom-bumping and lift-and-fall around structure efficiently target chinu for aggressive strikes.',
  'madai-crankbait':
    'Leveraging crankbait wobble and diving capability to directly target the red sea bream swimming layer. Combining pauses with movement during slow retrieves triggers reaction strikes from actively feeding fish.',
  'madai-minnow':
    'A slender profile with sharp wobble-and-roll stimulates red sea bream appetite. When tai-rubber fails to produce or surface schools appear, minnows serve as the trump card for drawing explosive strikes from trophy fish.',
  'madai-other':
    'An unconventional lure collection that coaxes bites from red sea bream when tai-rubber and jigging standards fall short. Reading subtle shifts in current and water temperature for selective lure changes is what separates catch rates.',
  'madai-sinking-pencil':
    'The steady-retrieve drift of a slow-sinking pencil traces the red sea bream strike zone for an extended distance. A slender profile and natural swim serve as the ultimate weapon for deceiving wary trophy specimens.',
  'madai-worm':
    'The extremely natural wave action of soft plastics flips the red sea bream switch. Rigs with jigheads or offset hooks cover a wide range from surface to mid-water, coaxing bites from pressured fish as the finesse option.',
  'rockfish-diving-pencil':
    'The aggressive splash and diving action of a diving pencil stimulates rockfish territorial behavior. Cast to rocky points and work the action to draw fish charging out of their lairs.',
  'rockfish-other':
    'Unique lures for diverse rockfish terrain expand the game\'s tactical arsenal. Independent approaches that excel where Texas rigs cannot reach or when reaction strikes are needed produce breakthrough results.',
  'rockfish-popper':
    'Popper splash stimulates the rockfish predatory instinct. Drop a popper tight to rocky shorelines and reef structure, then work short jerks to draw grouper and scorpionfish up for spectacular surface strikes.',
  'rockfish-spintail':
    'Spintail blade flash and strong wave action trigger reaction strikes from rockfish. Steady retrieves and lift-and-fall around structure cover a wide range, with a strong track record on scorpionfish and rockfish species.',
  'rockfish-topwater':
    'Topwater rockfish games deliver excitement beyond imagination. Drop a lure tight to the rocks and let it struggle on the surface — scorpionfish and grouper will charge up from their lairs for thrilling surface strikes.',
  'mebaru-jointed-bait':
    'The soft S-curve from a jointed body stimulates the rockfish predatory instinct. Dead-slow retrieves around streetlights and seaweed beds coax following fish into unhesitating bites with outstanding finesse capability.',
  'mebaru-metal-jig':
    'The fast fall and flash of a small metal jig triggers rockfish reactions. Covering everything from streetlight-lit jetties to deep rocky zones, leveraging casting distance to target migrating rockfish offshore.',
  'mebaru-other':
    'Approaches outside the standard rockfish toolbox crack pressured fish. Float rigs, plugging, and other diverse techniques open breakthroughs against fish that have been refusing everything else.',
  'mebaru-pencilbait':
    'Watching rockfish respond to a pencil swimming dead-slow just below the surface is supremely engaging. Matching the sightline of rockfish targeting bait around streetlights delivers explosive surface bites.',
  'mebaru-spintail':
    'Spintail blade flash strongly appeals to rockfish vision. Even a simple steady retrieve produces a natural fluttering swim that efficiently collects rockfish from surface to mid-water — a versatile all-rounder.',
  'aji-jointed-bait':
    'The soft jointed movement naturally triggers horse mackerel feeding. Dead-slow surface retrieves around streetlights deliver bites as fish detect the subtle tail vibration and inhale the lure. Upsizing potential is also strong.',
  'aji-minnow':
    'A slender-profile minnow syncs with the horse mackerel bait pattern. Counting down to establish the range and then slow-retrieving efficiently picks off fish from the edges of the school — outstanding practical performance.',
  'aji-other':
    'An unconventional lure collection that excels in situations where standard horse mackerel rigs fall short. The ability to select optimal approaches based on current, depth, and fish activity enables both numbers and trophy-size pursuits.',
  'aji-sinking-pencil':
    'A sinking pencil that freely segments depth via countdown directly targets the horse mackerel cruising layer. Dead-slow steady retrieves with minimal wave action coax natural bites from pressured fish around clear-water streetlight zones.',
  'aji-spintail':
    'Micro spintail blade flash locks horse mackerel vision onto a single point. Consistent catches on a simple steady retrieve alone make it an extremely reliable lure for long-cast wind days and deep-zone horse mackerel tactics.',
  'aji-vibration':
    'Vibration wave action stimulates the horse mackerel lateral line to trigger reaction strikes. Quickly establishing depth ranges even in strong current or deep-holding situations, it excels in efficient count-building run-and-gun sessions.',
  'aori-ika-sutte':
    'The color and posture changes of squid jigs simultaneously stimulate curiosity and predatory instinct. Mastering the timing to draw the embrace during the post-snap fall is the essence of squid fishing — the weight of a big squid committing is an incomparable sensation.',
  'aori-ika-worm':
    'Soft-bodied tip-run jigs and worms appeal to the squid\'s delicate tactile senses. Dead falls and slow snaps in current deliver exceptionally high finesse performance against pressured squid.',
  // ── Batch 3 ──
  'hiramasa-minnow':
    'Realistic baitfish silhouettes and wobbling action stimulate the predatory instinct of migrating amberjack. Tight attacks along rocky wash zones and current seams produce explosive strikes.',
  'hiramasa-other':
    'A lure collection that expands the amberjack tactical arsenal. Deploying type-matched selections for varying situations opens bite opportunities even when standard approaches fail.',
  'hiramasa-pencilbait':
    'If you want to experience amberjack breaking the surface, the pencil bait is the only choice. Walking the dog with side-to-side head shakes draws competing strikes and towering water columns from amberjack in the blitz zone. Pure topwater pelagic fishing at its finest.',
  'hiramasa-sinking-pencil':
    'A sinking pencil that balances casting range with versatile action is a cornerstone lure for the amberjack game. Adapting from steady retrieves to twitching, it efficiently searches a wide range from surface to mid-water.',
  'kampachi-minnow':
    'Greater amberjack frequently show reflex strikes to minnows. Creating feeding windows through speed reeling and jerking to trigger reaction bites is the textbook approach. The rod-screaming fight that follows is unforgettable.',
  'kampachi-other':
    'Successful greater amberjack fishing demands situation-aware lure selection. Approaches that produce during low-activity or lock-jaw conditions maximize your chances of connecting with that incredible power.',
  'kampachi-popper':
    'For explosive surface action, the popper is the best choice. The cup catches water, producing spray and noise that stimulate the greater amberjack attack instinct for violent strikes. The exhilaration of pelagic topwater fishing is unmatched.',
  'kampachi-sinking-pencil':
    'A sinking pencil reading the current to cover wide areas is effective on migrating greater amberjack. High castability reaches offshore current seams, turning encounters with trophy-class fish into reality.',
  'tuna-other':
    'Targeting tuna demands extraordinary casting distance and robust tackle. These are the options for drawing in big fish from distant blitzes and current seams, then prevailing in overwhelmingly powerful fights.',
  'tuna-pencilbait':
    'Pursuing tuna topwater bites on the open ocean. Cast a pencil bait to distance, work it on the surface, and flip the feeding switch on cruising tuna. The piercing strike and epic fight represent the pinnacle of offshore fishing.',
  'tuna-sinking-pencil':
    'When the blitz is distant or fish are focused mid-water, sinking pencils prove their worth. Counting down to match the range and working the action at the tuna cruising layer creates reliable bite opportunities.',
  'yellowtail-minnow':
    'Yellowtail readily show reaction strikes to minnows. Jerking and speed-reeling portray fleeing bait to draw chase-and-strike sequences. Winter yellowtail season sees particularly strong responses, with proven results targeting trophy-class fish.',
  'yellowtail-other':
    'A diverse lure collection that broadens yellowtail tactics. The optimal approach shifts with water temperature, current, and bait species — matching your selection to conditions maximizes encounter rates.',
  'yellowtail-pencilbait':
    'Yellowtail topwater games deliver non-stop adrenaline. Walking the dog on the surface draws competitive strikes from schooling fish. Exceptional immediacy during surface blitzes makes this a pelagic topwater staple.',
  'yellowtail-sinking-pencil':
    'When yellowtail cruise the mid-water column or blitzes move offshore, sinking pencils prove reliable. Leveraging casting distance to search broadly while adjusting range through retrieve speed is the core tactic.',
  'gt-pencilbait':
    'The pencil bait is the star of the GT game. Launch 100mm-plus plugs to distance and drive powerful head shakes with rod work. Watching a giant trevally charge through the whitewash for a strike is a once-in-a-lifetime tropical fishing moment.',
  'magochi-bigbait':
    'For targeting trophy flathead, a big bait\'s commanding presence creates decisive differentiation. Bottom-oriented realistic swimming action draws big fish in, elevating the flatfish game to the next level.',
  'magochi-metal-jig':
    'Flathead metal jig tactics center on one-pitch jerks after touching bottom. Working the jig slowly while re-establishing bottom contact puts it directly in front of sand-burrowed flathead. Ideal for efficiently searching deep surf and harbor zones.',
  'magochi-minnow':
    'Flathead strike when a minnow is retrieved just above the bottom. Slowly retrieving a lipped floating minnow while making occasional bottom contact creates sand puffs that attract flathead — a fundamental surf technique.',
  'magochi-pencilbait':
    'When flathead turn their attention to the surface, pencil bait topwater games become viable. The violent topwater strikes from what seems like a bottom-dwelling species deliver the full excitement of game fishing.',
  'magochi-swimbait':
    'A swimbait\'s realistic swimming action is strong during selective flathead feeding periods. Subtle tail vibration in the near-bottom feeding zone draws flathead in from distance.',
  'magochi-worm':
    'Jighead rigs are the foundation of flathead soft plastic tactics. Dragging the bottom with occasional shakes to imitate goby and worm movement delivers high finesse capability and consistent results even on pressured waters.',
  'kasago-jighead':
    'Scorpionfish are aggressive biters on jighead rigs. Drop the rig into tetrapod gaps and along structure edges with a slow bottom retrieve for continuous strikes. An accessible light-game staple from beginner to expert.',
  'kasago-vibration':
    'Vibration lure tight action stimulates the scorpionfish predatory instinct. Lift-and-fall around rocky reefs and structure efficiently targets bottom-dwelling scorpionfish.',
  'kasago-worm':
    'Soft plastics are among the most reliable lures for scorpionfish. Shrimp and worm profiles rigged Texas-style or on drop shots and delivered into rocky crevices produce reliable bites.',
  'hata-metal-jig':
    'Grouper respond strongly to metal jig falls. Mixing slack jerks near the bottom draws aggressive strikes from bottom-hugging grouper. Metal jigs are essential for deep rockfish territory.',
  'hata-worm':
    'Grouper species respond exceptionally well to the natural movement of soft plastics. Texas rigs and leaderless drop shots delivered into rocky structure and presented slowly near the bottom produce reliable bites as the standard approach.',
  'catfish-topwater':
    'Catfish topwater action explodes on nighttime rivers. The thunderous strike on a surface lure is addictive once experienced. Poppers and noisy surface baits that generate sound while working are the textbook method.',
  'snakehead-frog':
    'The frog is the absolute star of snakehead fishing. Skating it across cover and pausing at an open-water edge produces explosive strikes. A thrilling game targeting trophy snakehead holding in heavy cover.',
  'sweetfish-minnow':
    'Sweetfish lure fishing centers on minnow-based approaches that imitate traditional friend-fishing techniques. A minnow matched to real sweetfish swims naturally through the current, triggering territorial attack strikes from wild fish. Enjoy the mountain stream atmosphere and spirited fight simultaneously.',
  'ayu-minnow':
    'Ayu minnows are the cornerstone of lure fishing that exploits the sweetfish territorial behavior. Swimming a lure with virtually the same silhouette as a live decoy around riverbed rocks provokes territorial attacks from aggressive wild sweetfish. Ideal for clear-water stream game fishing.',
  'cuttlefish-egi':
    'Cuttlefish jigging is based on a slow, bottom-oriented style in shallow waters. Flashy snapping is unnecessary — simply placing the jig on the bottom and slowly dragging produces embraces. An excellent entry point to squid jigging.',
  'squid-egi':
    'Squid jigging uses shrimp-and-small-fish-imitating jigs to attract squid. The combination of rod snaps and falls draws squid interest, and setting the embrace during the fall is the core thrill of the sport.',
  'squid-other':
    'A fresh approach targeting squid with lures beyond conventional jigs and droppers. Diverse rigs and techniques enable distinctly different tactics, opening new possibilities for squid fishing on pressured grounds.',
  'squid-sutte':
    'Dropper jigs appeal strongly to squid vision and lateral line. Glow and luminescent materials are devastatingly effective for night fishing and boat jigging. Pairing as a dropper with a main jig is a standard tactic that significantly boosts catch rates.',
  'yari-ika-sutte':
    'Spear squid respond well to dropper jigs, making boat-based jigging the mainstream approach. Multi-hook dropper rigs enable double and triple hookups. From winter through spring spawning season, shore casting games also become viable.',
  'kensaki-ika-sutte':
    'Swordtip squid react swiftly to dropper jigs, and the active snap-triggered reaction strikes feel incredibly satisfying. Night sessions from jetties or offshore boats targeting light-attracted schools produce big hauls.',
  'octopus-egi':
    'Octopus jigs are purpose-designed lures with rubber tentacles and curly tails that trigger embraces. Simply dragging the bottom with added shaking while the snag-resistant design makes rocky reef tactics manageable.',
  'octopus-other':
    'Octopus fishing demands specialized rigs and strategy. Dedicated octopus lures and setups target large specimens around reefs and wave-dissipating blocks. Securing the embrace quickly and retrieving promptly is the core skill of octopus fishing.',
  'octopus-worm':
    'Octopus can also be reliably targeted with soft plastic rigs. The soft texture avoids triggering rejection, buying time for the octopus to fully commit. Paired with Texas rigs or bullet sinkers for thorough structure probing.',
  'saltwater-sutte':
    'Saltwater dropper jig fishing has a strong track record around nighttime streetlights and fishing ports. Glow and luminescent materials intensely attract squid species, enabling efficient numbers fishing with float rigs and boat drifting.',
  'saltwater-tai-rubber':
    'Tai-rubber commands enormous confidence in saltwater fishing. Despite its simple head-and-rubber construction, a constant-speed retrieve stimulates the feeding instinct. Outstanding versatility covering red sea bream and many other species.',
  'saltwater-worm':
    'Soft plastics are indispensable in saltwater fishing. Their natural action breaks through tough-bite situations, reliably drawing strikes in scenarios where hardbaits struggle.',
  'offshore-diving-pencil':
    'Diving pencils are the standard for offshore casting games. Rod-work-driven subsurface diving action generates unique wave displacement that draws pelagics from a wide area. A topwater lure purpose-built for big-game offshore encounters.',
  'offshore-metal-jig':
    'Offshore metal jigs are the versatile workhorses that search from deep to surface. The foundational one-pitch jerk draws the fish in while the fall secures the bite. Adaptable across high-speed jigging through slow-pitch styles.',
  'offshore-pencilbait':
    'Pencil baits command an overwhelming presence in offshore casting games. Long-casting toward bird piles and surface blitzes with powerful walking-the-dog action calls trophy pelagics to the surface — the star of big-game offshore fishing.',
  'mahi-mahi-diving-pencil':
    'Mahi-mahi produce spectacular strikes on diving pencils. Casting along current seams and working subsurface with erratic action draws brilliantly colored mahi-mahi competing for the strike.',
  'mahi-mahi-minnow':
    'Mahi-mahi respond strongly to the lip-driven wobbling action of minnows. Speed-reeling and jerking to portray fleeing bait lets you experience the spectacular leaping strikes and powerful fight of mahi-mahi across blue ocean waters.',
  'mahi-mahi-popper':
    'Mahi-mahi popper fishing delivers non-stop visual excitement. Working the cup to produce sound and spray draws gold-and-green mahi-mahi into fearless strikes. A full experience of offshore topwater game fishing at its finest.',
  'tachiuo-other':
    'Cutlassfish are targetable through diverse approaches from bait-wrapped tenya to lures. Specialized tackle handles their razor-sharp teeth and unique bite patterns, and the excitement of that ribbon-like body thrashing on the surface is unforgettable.',
  'tachiuo-tenya':
    'Tenya holds an unshakeable position in cutlassfish boat fishing. Bait-wrapped tenya worked with falls and retrieves exploits the characteristic upward-feeding bite pattern for reliable hooksets — the definitive style of boat-based cutlassfish fishing.',
  // ── Batch 4 ──
  'aji-pencilbait':
    'Pencil bait subsurface walking the dog establishes a viable topwater game for trophy horse mackerel. Slow-retrieving to match the feeding range of bait-chasing fish around streetlights delivers the pure thrill of plugging-style ajing.',
  'aji-metal-vib':
    'The high-density body of a metal vibe maintains casting distance even into headwinds, proving its worth for daytime deep-zone horse mackerel tactics. Lift-and-fall presentations quickly locate the school\'s depth for efficient numbers fishing.',
  'seabass-frog':
    'A frog\'s natural splashdown sound and slow movement draw seabass out from under cover. Weed areas and dock undercuts can be fished snag-free, and the surface explosion on the bite is exceptional.',
  'seabass-rubber-jig':
    'Rubber jig skirt action and slow fall appeal to near-bottom seabass. Carefully dropping along bridge piling bases and submerged structure pulls out resident fish that ignore standard hardbaits.',
  'kurodai-crankbait':
    'Crankbait wide wobble stimulates black sea bream curiosity. Tracing along shallow cobble and riprap with lip contact triggers reaction strikes — gaining attention as a fresh approach to chinu fishing.',
  'chinu-kurodai-popper':
    'Poppers are essential for chinu topwater games. Popping action on tidal flats and shallow areas produces explosive surface strikes from black sea bream. Dawn and dusk windows are the prime time.',
  'madai-jighead':
    'A light jighead-and-worm approach for red sea bream. When tai-rubber fails during low-activity periods, slow falls and shaking produce a suction-type bite from red sea bream.',
  'hirame-jighead':
    'Jighead rigs deliver the highest-precision bottom approach for flounder. Lift-and-fall after touching bottom puts the worm within range of sand-burrowed flounder, reliably connecting on upward-feeding fall bites.',
  'hirame-spinnerbait':
    'Spinnerbait blade flash and skirt wave action attract surf flounder from a wide area. Slow-rolling near the bottom lets blade flash flip the feeding switch on sand-buried flounder.',
  'catfish-crawler-bait':
    'Crawler bait surface action and distinctive water noise drive catfish wild. Slow-retrieving through nighttime rivers and drainage channels produces thunderous strikes that deliver the full catfish game excitement.',
  // Pelagic compound names
  'bluerunner-all-pencilbait':
    'Walking the dog with a pencil bait is the ultimate topwater choice for all pelagic species. Watching yellowtail, amberjack, and greater amberjack break the surface for a strike creates memories etched deep in every angler. Outstanding immediacy for surface-blitz situations.',
  'bluerunner-all-sinking-pencil':
    'Sinking pencils provide high versatility across all pelagic targets. Counting down to match the range targets everything from yellowtail to greater amberjack. Casting distance and action versatility make it a shore-fishing mainstay.',
  'bluerunner-all-metal-jig':
    'The metal jig is the backbone of pelagic fishing. From shore to offshore, one-pitch and slow-pitch jerks horizontally target yellowtail, amberjack, and greater amberjack. Weight and silhouette selection determine the day\'s catch rate.',
  'bluerunner-all-blade-bait':
    'Blade bait high-speed vibration and flash trigger reaction strikes across all pelagic species. Efficient steady-retrieve searching covers wide areas, and encountering a migrating school can produce chain hookups.',
  'bluerunner-all-diving-pencil':
    'The diving pencil is the showpiece of pelagic casting games from rocky shores and surf. Rod-work-driven subsurface diving action directly targets the predatory instinct of all pelagic species from yellowtail to amberjack.',
  // Rockfish and trout compound names
  'rockfish-all-metal-jig':
    'Metal jigs are ideal for deep-water rockfish tactics across all species. Lift-and-fall from rocky shores or boats efficiently targets scorpionfish, lingcod, and grouper alike. The flutter on the fall serves as the primary bite trigger.',
  'rockfish-all-jighead':
    'Jighead rigs are the standard rockfish approach. Delivering worms into tetrapod gaps and rocky reefs with a slow bottom probe produces reliable bites from scorpionfish and lingcod. Fine-tuning head weight is what separates catch rates.',
  'trout-all-crankbait':
    'Crankbaits are versatile all-rounders from managed fisheries to native trout waters. Matching range via lip diving angle and tight wobble coaxes bites from even the most reluctant trout.',
  'trout-all-minnow':
    'Minnows are the foundation of all trout fishing. From managed-fishery rainbows to mountain stream char, the classic twitch-and-pause action draws bites even from pressured fish.',
  'trout-all-jighead':
    'Jighead rigs cover everything from trout bottom tactics to swimming presentations. From dead-slow managed-fishery sessions to fast-water main-river drifts, approach versatility expands with head-weight selection.',
  'trout-all-other':
    'Diverse lures outside standard spoon and spinner categories expand the trout game\'s tactical range. Unconventional approaches that become trump cards in tough conditions frequently make the difference in catch rates.',
  'trout-swimbait':
    'Swimbait realistic silhouettes and tail action stimulate the predatory instinct of trophy trout. Slow retrieves in lakes and main rivers are fundamental, matching the hatch when trout are keyed on smelt or minnows.',
  // Squid
  'squid-all-egi':
    'Squid jigs are the all-around lure for targeting every squid species from bigfin reef squid to spear squid. The snap-and-fall combination adapts to each species\' behavior patterns, with size and color selection by season and region determining success.',
  // North American freshwater — Crappie
  'crappie-worm':
    'Soft plastics are the most versatile lure in crappie fishing. Small curly tails and grubs on jigheads worked with a slow fall efficiently produce numbers from schooling crappie.',
  'crappie-jighead':
    'Jighead rigs are the gold standard for crappie. Micro worms on light jigheads slowly dropped around brush piles and submerged timber produce chain-reaction bites from schooling fish.',
  'crappie-swimbait':
    'The realistic shad-tail action of a swimbait triggers feeding responses from slab crappie. Slow-swimming along breaklines and structure edges opens the door to trophy-class encounters.',
  'crappie-rubber-jig':
    'Rubber jig skirt action stimulates crappie curiosity. Dropping tight to brush piles and weed edges with a slow fall draws concentrated bites from quality crappie.',
  'crappie-crankbait':
    'Crankbaits cover wide areas efficiently through trolling or casting for crappie. Deep-diving lip models are the key to matching depth during fall and winter deep-crappie patterns.',
  'crappie-minnow':
    'A minnow\'s tight wobble matches the crappie bait pattern. Slow-retrieving around shallow brush piles coaxes bites from suspended schooling crappie.',
  // North American — Redfish
  'redfish-worm':
    'Soft plastics are a staple of redfish fishing. Shad tails and paddle tails on jigheads worked carefully around flats and marsh shorelines produce reliable bites.',
  'redfish-jighead':
    'Jighead rigs are ideal for redfish sight-fishing. Cast ahead of tailing fish on shallow flats and work a slow bottom retrieve for immediate strikes.',
  'redfish-swimbait':
    'A swimbait\'s realistic baitfish action stimulates the predatory instinct of trophy redfish. Slow-retrieving around marshes and flats delivers powerful strikes and an incredible fight from bull reds.',
  'redfish-spinnerbait':
    'Spinnerbait blade flash and skirt wave action appeal aggressively to redfish in murky water. Slow-rolling along marsh shorelines catches redfish across a wide area.',
  'redfish-topwater':
    'Redfish topwater fishing takes visual excitement to the maximum. Casting poppers and walking baits at shallow-flat fish chasing bait produces explosive surface strikes.',
  'redfish-minnow':
    'Minnows are central to redfish match-the-hatch strategies. Twitch-and-pause presentations along shorelines and docks trigger chain-reaction strikes.',
  'redfish-jerkbait':
    'Jerkbait darting action triggers redfish reaction strikes. Jerk-and-pause sequences on clear-water flats draw committed bites from trailing redfish.',
  // North American — Snook
  'snook-worm':
    'Soft plastics are the most reliable lure for snook. Dropping jighead rigs into mangrove roots and dock structure with slow presentations draws snook charging out to strike.',
  'snook-swimbait':
    'A swimbait\'s realistic swim engages the big-snook feeding switch. Matching size to mullet and pilchard profiles to work inlets and beachfronts is the core strategy.',
  'snook-rubber-jig':
    'Rubber jigs are ideal for snook structure fishing. Flipping into dock pilings and seawall edges draws powerful bites from big snook holding tight to structure.',
  'snook-topwater':
    'Snook topwater strikes deliver explosive power. Deploy walking baits and poppers during pre-dawn and sunset windows for the violent snook-specific surface strikes.',
  'snook-minnow':
    'A minnow\'s tight action effectively targets snook around mangroves. Twitch-and-pause presentations accurately replicate baitfish movement in ambush zones.',
  'snook-spinnerbait':
    'Spinnerbait blade flash draws snook out of mangroves and marsh cover. Deflecting through cover for wide-area searching, with particular devastating effect during low-light conditions.',
  'snook-jerkbait':
    'Jerkbait erratic darts trigger snook reaction strikes. Jerk-and-pause sequences around clear-water flats and inlets draw fearless attacks from snook.',
  // North American — Seatrout
  'seatrout-worm':
    'Soft plastics deliver consistent seatrout results across all seasons. Slowly probing grass flats and sandbars with jigheads produces chain hookups from schooling fish.',
  'seatrout-swimbait':
    'A swimbait\'s realistic baitfish action directly targets the seatrout feeding range. Slow-retrieving around grass flats can produce encounters with trophy-class gator trout.',
  'seatrout-topwater':
    'Seatrout topwater games reach their peak on dawn shallow-flat sessions. Surface-explosion strikes on walking baits and poppers are the essence of inshore game fishing.',
  'seatrout-jerkbait':
    'Subsurface darting action from a jerkbait triggers seatrout reaction bites. Jerk-and-pause combinations on clear-water grass flats deliver consistent results.',
  // North American — Walleye
  'walleye-crankbait':
    'Crankbaits are the primary lure in walleye fishing. Trolling to cover wide areas while matching suspended-fish depth via lip diving range is the strategy that determines success.',
  'walleye-worm':
    'Worm rigs reach their full potential during slow walleye presentations. Slowly dragging the bottom with live-bait-rig sensibilities lets you detect the characteristically delicate walleye bite.',
  'walleye-swimbait':
    'A swimbait\'s realistic action matches walleye selective-feeding patterns. Slow-retrieving deep breaks and humps targets trophy-class walleye.',
  'walleye-minnow':
    'Minnow wobble-and-roll directly targets the walleye feeding range. Twitch-and-pause portray wounded baitfish to trigger reaction strikes.',
  'walleye-vibration':
    'Vibration lure wave action stimulates the walleye lateral line. Deep lift-and-fall and bottom-bumping efficiently trigger reaction bites from inactive walleye.',
  'walleye-jighead':
    'Jighead rigs are the absolute foundation of walleye fishing. Bouncing minnow or worm combos along rocky and gravel bottoms reliably produces bites.',
  'walleye-rubber-jig':
    'Rubber jig slow falls and skirt action match walleye bottom-feeding behavior. Methodically working rocky bottoms and brush piles precisely targets areas holding big fish.',
  // North American — Striped Bass
  'striped-bass-worm':
    'Soft plastics deliver results through striped bass finesse approaches. Slow bottom presentations with jigheads and drop shots coax bites even on pressured waters.',
  'striped-bass-swimbait':
    'A swimbait\'s oversized profile and realistic tail action awaken the predatory instinct of trophy striped bass. Heavy models slowly worked through reservoir and river deep zones target the biggest fish.',
  'striped-bass-rubber-jig':
    'Rubber jigs are ideal for striped bass structure fishing. Flipping into dam intakes and bridge pilings draws powerful strikes from big stripers holding tight to structure.',
  // North American — Pike
  'pike-worm':
    'Pike attack large worm jerkbait rigs with ferocity. Showing slow movement along weed edges and lily pad zones draws aggressive charges.',
  'pike-swimbait':
    'An oversized swimbait profile maximally stimulates the pike predatory instinct. Slow-retrieving weed flats produces explosive upward-thrusting strikes from trophy pike.',
  'pike-frog':
    'Frogs are the ultimate choice for pike weed-mat games. Skating across lily pads and pausing on open pockets produces the explosive surface strikes pike are famous for.',
  'pike-crankbait':
    'Crankbait wide wobble simultaneously stimulates pike vision and lateral line. Fast retrieves along weed edges and rock piles produce chain-reaction strikes.',
  // North American — Panfish
  'panfish-worm':
    'Soft plastics are the most reliable lure for panfish species including bluegill and sunfish. Micro-sized grubs and worms on light jigheads enable delicate approaches for enjoyable numbers fishing.',
  'panfish-jighead':
    'Jighead rigs are ideal for panfish pinpoint tactics. Dropping micro jigs into brush piles where bluegill and crappie school produces continuous bites.',
  'panfish-swimbait':
    'Micro swimbait realistic tail action enables a selective approach targeting trophy panfish. Slow-retrieving along breaklines and weed edges opens encounters with slab-sized bluegill.',
  'panfish-rubber-jig':
    'Micro rubber jig skirt action attracts panfish curiosity. Slow-fall presentations around brush piles and dock pilings draw concentrated bites from quality bluegill and sunfish.',
  // North American — Perch
  'perch-worm':
    'Soft plastics are a staple of perch fishing. Micro curly tails and grubs on drop shots efficiently build numbers from schooling perch.',
  'perch-swimbait':
    'A swimbait\'s realistic action matches perch feeding patterns. Slow-retrieving rocky bottoms and weed edges draws competitive bites from quality perch.',
  'perch-crankbait':
    'Crankbait vibration and flash attract perch schools from a wide area. Tight retrieves along rocky shorelines and breakpoints efficiently produce bites from schooling fish.',
  'perch-spinnerbait':
    'Spinnerbait blade flash strongly appeals to perch vision. Slow-rolling along weed edges and drop-offs produces chain hookups from the moment you locate a school.',
  // Final additions
  'tachiuo-lure-accessory':
    'Accessories such as assist hooks, blades, and glow sticks significantly impact cutlassfish catch rates. Wire leaders and tuning parts designed for razor-sharp teeth ensure stable hooksets and successful landing.',
  'aji-shad':
    'A shad\'s tight wobble matches horse mackerel micro bait patterns. Dead-slow surface retrieves around streetlights produce chain bites from plankton-feeding schools.',
  'mebaru-shad':
    'A shad\'s subtle vibration stimulates the rockfish predatory instinct. Slow-retrieving along the light-shadow boundary around streetlights delivers the precision finesse of plugging-style rockfish fishing. Especially strong in clear water.',
  'crappie-spinnerbait':
    'Spinnerbait blade flash draws crappie from a wide area in stained water. Slow-rolling around brush piles produces chain bites from schooling crappie.',
};
